<?php

namespace ContainerKp5Xx2P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_T2GGs3tService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.T2GGs3t' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.T2GGs3t'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'structure' => ['privates', '.errored..service_locator.T2GGs3t.Sulu\\Component\\Content\\Compat\\StructureInterface', NULL, 'Cannot autowire service ".service_locator.T2GGs3t": it references interface "Sulu\\Component\\Content\\Compat\\StructureInterface" but no such service exists. Did you create a class that implements this interface?'],
        ], [
            'structure' => 'Sulu\\Component\\Content\\Compat\\StructureInterface',
        ]);
    }
}
