<?php

namespace ContainerKp5Xx2P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_W1tc2kYService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.W1tc2kY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.W1tc2kY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'Sulu\\Bundle\\WebsiteBundle\\Controller\\DefaultController::indexAction' => ['privates', '.service_locator.T2GGs3t', 'get_ServiceLocator_T2GGs3tService', true],
            'sulu_website.default_controller::indexAction' => ['privates', '.service_locator.T2GGs3t', 'get_ServiceLocator_T2GGs3tService', true],
            'sulu_website.default_controller:indexAction' => ['privates', '.service_locator.T2GGs3t', 'get_ServiceLocator_T2GGs3tService', true],
        ], [
            'Sulu\\Bundle\\WebsiteBundle\\Controller\\DefaultController::indexAction' => '?',
            'sulu_website.default_controller::indexAction' => '?',
            'sulu_website.default_controller:indexAction' => '?',
        ]);
    }
}
