<?php

namespace ContainerKp5Xx2P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsole_Command_PublicAlias_MassiveBuild_Command_BuildService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'console.command.public_alias.massive_build.command.build' shared service.
     *
     * @return \Sulu\Bundle\CoreBundle\CommandOptional\SuluBuildCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['console.command.public_alias.massive_build.command.build'] = new \Sulu\Bundle\CoreBundle\CommandOptional\SuluBuildCommand(($container->privates['massive_build.build.registry'] ?? $container->load('getMassiveBuild_Build_RegistryService')), $container);
    }
}
