<?php

namespace ContainerKp5Xx2P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrinePhpcr_Jackalope_Repository_DefaultService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'doctrine_phpcr.jackalope.repository.default' shared service.
     *
     * @return \Jackalope\Repository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['doctrine_phpcr.jackalope.repository.default'] = ($container->privates['doctrine_phpcr.jackalope.repository.factory.service.doctrinedbal'] ?? ($container->privates['doctrine_phpcr.jackalope.repository.factory.service.doctrinedbal'] = new \Jackalope\RepositoryFactoryDoctrineDBAL()))->getRepository(['jackalope.doctrine_dbal_connection' => ($container->services['doctrine.dbal.default_connection'] ?? $container->getDoctrine_Dbal_DefaultConnectionService()), 'jackalope.check_login_on_server' => false]);
    }
}
