<?php

namespace ContainerKp5Xx2P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDtlContent_Form_Type_PageService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'dtl_content.form.type.page' shared service.
     *
     * @return \Sulu\Bundle\PageBundle\Form\Type\PageDocumentType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['dtl_content.form.type.page'] = new \Sulu\Bundle\PageBundle\Form\Type\PageDocumentType(($container->services['sulu.phpcr.session'] ?? $container->getSulu_Phpcr_SessionService()), ($container->services['sulu_document_manager.document_manager'] ?? $container->getSuluDocumentManager_DocumentManagerService()), ($container->privates['sulu_document_manager.metadata_factory'] ?? $container->getSuluDocumentManager_MetadataFactoryService()));
    }
}
