<?php

namespace ContainerKp5Xx2P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getErrorControllerService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'error_controller' shared service.
     *
     * @return \Sulu\Bundle\WebsiteBundle\Controller\ErrorController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['error_controller'] = new \Sulu\Bundle\WebsiteBundle\Controller\ErrorController(($container->privates['sulu_website.error_controller.inner'] ?? $container->load('getSuluWebsite_ErrorController_InnerService')), ($container->services['sulu_website.resolver.template_attribute'] ?? $container->load('getSuluWebsite_Resolver_TemplateAttributeService')), ($container->services['.container.private.twig'] ?? $container->get_Container_Private_TwigService()), true);
    }
}
