<?php

namespace ContainerKp5Xx2P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHandcraftedinthealpsRestRouting_Loader_YamlCollectionService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'handcraftedinthealps_rest_routing.loader.yaml_collection' shared service.
     *
     * @return \HandcraftedInTheAlps\RestRoutingBundle\Routing\Loader\RestYamlCollectionLoader
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['handcraftedinthealps_rest_routing.loader.yaml_collection'] = new \HandcraftedInTheAlps\RestRoutingBundle\Routing\Loader\RestYamlCollectionLoader(($container->privates['file_locator'] ?? ($container->privates['file_locator'] = new \Symfony\Component\HttpKernel\Config\FileLocator(($container->services['kernel'] ?? $container->get('kernel', 1))))), ($container->privates['handcraftedinthealps_rest_routing.loader.processor'] ?? ($container->privates['handcraftedinthealps_rest_routing.loader.processor'] = new \HandcraftedInTheAlps\RestRoutingBundle\Routing\Loader\RestRouteProcessor())), true, ['json' => true, 'csv' => true], 'json');
    }
}
