<?php

namespace ContainerKp5Xx2P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMassiveSearch_Reindex_ProviderRegistryService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'massive_search.reindex.provider_registry' shared service.
     *
     * @return \Massive\Bundle\SearchBundle\Search\Reindex\ReindexProviderRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['massive_search.reindex.provider_registry'] = $instance = new \Massive\Bundle\SearchBundle\Search\Reindex\ReindexProviderRegistry();

        $instance->addProvider('doctrine_orm', ($container->privates['massive_search.reindex.provider.doctrine_orm'] ?? $container->load('getMassiveSearch_Reindex_Provider_DoctrineOrmService')));
        $instance->addProvider('sulu_structure', ($container->privates['sulu_page.search.reindex.structure_provider'] ?? $container->load('getSuluPage_Search_Reindex_StructureProviderService')));

        return $instance;
    }
}
