<?php

namespace ContainerKp5Xx2P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNodeDumpCommandService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'console.command.public_alias.Doctrine\Bundle\PHPCRBundle\Command\NodeDumpCommand' shared service.
     *
     * @return \Doctrine\Bundle\PHPCRBundle\Command\NodeDumpCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['console.command.public_alias.Doctrine\\Bundle\\PHPCRBundle\\Command\\NodeDumpCommand'] = $instance = new \Doctrine\Bundle\PHPCRBundle\Command\NodeDumpCommand();

        $instance->setConsoleDumper(($container->privates['doctrine_phpcr.console_dumper'] ?? ($container->privates['doctrine_phpcr.console_dumper'] = new \PHPCR\Util\Console\Helper\PhpcrConsoleDumperHelper())));

        return $instance;
    }
}
