<?php

namespace ContainerKp5Xx2P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRouting_ResolverService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'routing.resolver' shared service.
     *
     * @return \Symfony\Component\Config\Loader\LoaderResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['routing.resolver'] = $instance = new \Symfony\Component\Config\Loader\LoaderResolver();

        $instance->addLoader(($container->privates['routing.loader.xml'] ?? $container->load('getRouting_Loader_XmlService')));
        $instance->addLoader(($container->privates['routing.loader.yml'] ?? $container->load('getRouting_Loader_YmlService')));
        $instance->addLoader(($container->privates['routing.loader.php'] ?? $container->load('getRouting_Loader_PhpService')));
        $instance->addLoader(($container->privates['routing.loader.glob'] ?? $container->load('getRouting_Loader_GlobService')));
        $instance->addLoader(($container->privates['routing.loader.directory'] ?? $container->load('getRouting_Loader_DirectoryService')));
        $instance->addLoader(($container->privates['routing.loader.container'] ?? $container->load('getRouting_Loader_ContainerService')));
        $instance->addLoader(($container->privates['handcraftedinthealps_rest_routing.loader.directory'] ?? $container->load('getHandcraftedinthealpsRestRouting_Loader_DirectoryService')));
        $instance->addLoader(($container->privates['handcraftedinthealps_rest_routing.loader.controller'] ?? $container->load('getHandcraftedinthealpsRestRouting_Loader_ControllerService')));
        $instance->addLoader(($container->privates['handcraftedinthealps_rest_routing.loader.yaml_collection'] ?? $container->load('getHandcraftedinthealpsRestRouting_Loader_YamlCollectionService')));
        $instance->addLoader(($container->privates['handcraftedinthealps_rest_routing.loader.xml_collection'] ?? $container->load('getHandcraftedinthealpsRestRouting_Loader_XmlCollectionService')));
        $instance->addLoader(($container->privates['sulu_website.routing.portal_loader'] ?? $container->load('getSuluWebsite_Routing_PortalLoaderService')));
        $instance->addLoader(($container->privates['sulu_document_manager.routing.version_loader'] ?? ($container->privates['sulu_document_manager.routing.version_loader'] = new \Sulu\Bundle\DocumentManagerBundle\Routing\Loader\VersionRouteLoader(false))));
        $instance->addLoader(($container->privates['routing.loader.annotation'] ?? $container->load('getRouting_Loader_AnnotationService')));
        $instance->addLoader(($container->privates['routing.loader.annotation.directory'] ?? $container->load('getRouting_Loader_Annotation_DirectoryService')));
        $instance->addLoader(($container->privates['routing.loader.annotation.file'] ?? $container->load('getRouting_Loader_Annotation_FileService')));

        return $instance;
    }
}
