<?php

namespace ContainerKp5Xx2P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_SmartContent_DataProvider_Content_ProxyFactoryService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_page.smart_content.data_provider.content.proxy_factory' shared service.
     *
     * @return \ProxyManager\Factory\LazyLoadingValueHolderFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_page.smart_content.data_provider.content.proxy_factory'] = new \ProxyManager\Factory\LazyLoadingValueHolderFactory(($container->privates['sulu_core.proxy_manager.configuration'] ?? $container->getSuluCore_ProxyManager_ConfigurationService()));
    }
}
