<?php

namespace ContainerKp5Xx2P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSulu_Content_WebspaceStructureProvider_CacheService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu.content.webspace_structure_provider.cache' shared service.
     *
     * @return \Doctrine\Common\Cache\FilesystemCache
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu.content.webspace_structure_provider.cache'] = new \Doctrine\Common\Cache\FilesystemCache(($container->targetDir.''.'/sulu/webspace_structures'));
    }
}
