<?php

namespace ContainerKp5Xx2P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_Search_Metadata_Provider_StructureService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_page.search.metadata.provider.structure' shared service.
     *
     * @return \Sulu\Bundle\PageBundle\Search\Metadata\StructureProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_page.search.metadata.provider.structure'] = new \Sulu\Bundle\PageBundle\Search\Metadata\StructureProvider(($container->privates['sulu_search.search.factory'] ?? ($container->privates['sulu_search.search.factory'] = new \Sulu\Bundle\SearchBundle\Search\Factory())), ($container->privates['sulu_document_manager.metadata_factory'] ?? $container->getSuluDocumentManager_MetadataFactoryService()), ($container->services['sulu_page.structure.factory'] ?? $container->getSuluPage_Structure_FactoryService()), ($container->services['sulu_page.extension.manager'] ?? $container->getSuluPage_Extension_ManagerService()), $container->parameters['sulu_page.search.mapping']);
    }
}
