<?php

namespace ContainerKp5Xx2P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_Import_WebspaceService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu_page.import.webspace' shared service.
     *
     * @return \Sulu\Component\Content\Import\WebspaceImport
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_page.import.webspace'] = new \Sulu\Component\Content\Import\WebspaceImport(($container->services['sulu_document_manager.document_manager'] ?? $container->getSuluDocumentManager_DocumentManagerService()), ($container->services['sulu_document_manager.document_inspector'] ?? $container->getSuluDocumentManager_DocumentInspectorService()), ($container->privates['sulu_document_manager.document_registry'] ?? ($container->privates['sulu_document_manager.document_registry'] = new \Sulu\Component\DocumentManager\DocumentRegistry('en'))), ($container->services['sulu_page.compat.structure.legacy_property_factory'] ?? $container->getSuluPage_Compat_Structure_LegacyPropertyFactoryService()), ($container->privates['sulu.content.resource_locator.strategy.tree_leaf_edit'] ?? $container->getSulu_Content_ResourceLocator_Strategy_TreeLeafEditService()), ($container->services['sulu.content.structure_manager'] ?? $container->getSulu_Content_StructureManagerService()), ($container->services['sulu_page.extension.manager'] ?? $container->getSuluPage_Extension_ManagerService()), ($container->privates['sulu_page.import.manager'] ?? $container->getSuluPage_Import_ManagerService()), ($container->privates['sulu_page.import.webspace.xliff12'] ?? ($container->privates['sulu_page.import.webspace.xliff12'] = new \Sulu\Component\Import\Format\Xliff12())), ($container->privates['logger'] ?? ($container->privates['logger'] = new \Symfony\Component\HttpKernel\Log\Logger())));
    }
}
