<?php

namespace ContainerKp5Xx2P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSulu_Content_Type_SinglePageSelectionService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu.content.type.single_page_selection' shared service.
     *
     * @return \Sulu\Bundle\PageBundle\Content\Types\SinglePageSelection
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu.content.type.single_page_selection'] = new \Sulu\Bundle\PageBundle\Content\Types\SinglePageSelection(($container->privates['sulu_page.reference_store.content'] ?? ($container->privates['sulu_page.reference_store.content'] = new \Sulu\Bundle\WebsiteBundle\ReferenceStore\ReferenceStore())));
    }
}
