<?php

namespace ContainerKp5Xx2P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_Command_CleanupHistoryService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_page.command.cleanup_history' shared service.
     *
     * @return \Sulu\Bundle\PageBundle\Command\CleanupHistoryCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine_phpcr.session'] ?? $container->getDoctrinePhpcr_SessionService());

        $container->privates['sulu_page.command.cleanup_history'] = $instance = new \Sulu\Bundle\PageBundle\Command\CleanupHistoryCommand(($container->services['sulu.phpcr.session'] ?? $container->getSulu_Phpcr_SessionService()), $a, $a);

        $instance->setName('sulu:content:cleanup-history');

        return $instance;
    }
}
