<?php

namespace ContainerKp5Xx2P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluMedia_CollectionManagerService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu_media.collection_manager' shared service.
     *
     * @return \Sulu\Bundle\MediaBundle\Collection\Manager\CollectionManager
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_media.collection_manager'] = new \Sulu\Bundle\MediaBundle\Collection\Manager\CollectionManager(($container->services['sulu_media.collection_repository'] ?? $container->getSuluMedia_CollectionRepositoryService()), ($container->services['sulu.repository.media'] ?? $container->getSulu_Repository_MediaService()), ($container->services['sulu_media.format_manager'] ?? $container->getSuluMedia_FormatManagerService()), ($container->services['sulu.repository.user'] ?? $container->getSulu_Repository_UserService()), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), NULL, 'sulu-50x50', $container->parameters['sulu_security.permissions']);
    }
}
