<?php

namespace ContainerKp5Xx2P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluHash_RequestHashCheckerService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu_hash.request_hash_checker' shared service.
     *
     * @return \Sulu\Component\Hash\RequestHashChecker
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_hash.request_hash_checker'] = new \Sulu\Component\Hash\RequestHashChecker(($container->privates['sulu_hash.auditable_hasher'] ?? ($container->privates['sulu_hash.auditable_hasher'] = new \Sulu\Component\Hash\AuditableHasher())));
    }
}
