<?php

namespace ContainerKp5Xx2P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSnippet_Import_Webspace_Xliff12Service extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_snippet.import.webspace.xliff12' shared service.
     *
     * @return \Sulu\Component\Import\Format\Xliff12
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_snippet.import.webspace.xliff12'] = new \Sulu\Component\Import\Format\Xliff12();
    }
}
