<?php

namespace ContainerKp5Xx2P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluCore_Build_Builder_FixturesService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_core.build.builder.fixtures' shared service.
     *
     * @return \Sulu\Bundle\CoreBundle\Build\FixturesBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_core.build.builder.fixtures'] = new \Sulu\Bundle\CoreBundle\Build\FixturesBuilder();
    }
}
