<?php

namespace ContainerKp5Xx2P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluDocumentManager_Initializer_WorkspaceService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu_document_manager.initializer.workspace' shared service.
     *
     * @return \Sulu\Bundle\DocumentManagerBundle\Initializer\WorkspaceInitializer
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_document_manager.initializer.workspace'] = new \Sulu\Bundle\DocumentManagerBundle\Initializer\WorkspaceInitializer(($container->services['doctrine_phpcr'] ?? $container->load('getDoctrinePhpcrService')));
    }
}
