<?php

namespace ContainerKp5Xx2P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluMedia_SystemCollections_CacheService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_media.system_collections.cache' shared service.
     *
     * @return \Sulu\Component\Cache\DataCache
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_media.system_collections.cache'] = new \Sulu\Component\Cache\DataCache(($container->targetDir.''.'/sulu/system_collection.cache'));
    }
}
