<?php

namespace ContainerKp5Xx2P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluCustomUrls_InitializerService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu_custom_urls.initializer' shared service.
     *
     * @return \Sulu\Component\CustomUrl\Document\Initializer\CustomUrlInitializer
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_custom_urls.initializer'] = new \Sulu\Component\CustomUrl\Document\Initializer\CustomUrlInitializer(($container->privates['sulu_document_manager.node_manager'] ?? $container->getSuluDocumentManager_NodeManagerService()), ($container->privates['sulu_document_manager.path_builder'] ?? $container->getSuluDocumentManager_PathBuilderService()), ($container->services['sulu_core.webspace.webspace_manager'] ?? $container->getSuluCore_Webspace_WebspaceManagerService()), ($container->services['sulu.phpcr.session'] ?? $container->getSulu_Phpcr_SessionService()));
    }
}
