<?php

namespace ContainerKp5Xx2P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_Teaser_Provider_ContentService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_page.teaser.provider.content' shared service.
     *
     * @return \Sulu\Bundle\PageBundle\Teaser\PageTeaserProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_page.teaser.provider.content'] = new \Sulu\Bundle\PageBundle\Teaser\PageTeaserProvider(($container->services['massive_search.search_manager'] ?? $container->load('getMassiveSearch_SearchManagerService')), ($container->services['translator'] ?? $container->getTranslatorService()), false, ($container->privates['sulu_page.teaser.provider.phpcr'] ?? $container->load('getSuluPage_Teaser_Provider_PhpcrService')));
    }
}
