<?php

namespace ContainerKp5Xx2P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluMedia_Type_ImageMapService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu_media.type.image_map' shared service.
     *
     * @return \Sulu\Bundle\MediaBundle\Content\Types\ImageMapContentType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_media.type.image_map'] = new \Sulu\Bundle\MediaBundle\Content\Types\ImageMapContentType(($container->services['sulu.content.type_manager'] ?? $container->getSulu_Content_TypeManagerService()));
    }
}
