<?php

namespace ContainerKp5Xx2P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluCore_Doctrine_ReferencesService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_core.doctrine.references' shared service.
     *
     * @return \Sulu\Component\Doctrine\ReferencesOption
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_core.doctrine.references'] = new \Sulu\Component\Doctrine\ReferencesOption(($container->services['doctrine'] ?? $container->getDoctrineService()), ['Sulu\\Bundle\\ContactBundle\\Entity\\ContactInterface' => 'Sulu\\Bundle\\ContactBundle\\Entity\\Contact', 'Sulu\\Bundle\\ContactBundle\\Entity\\AccountInterface' => 'Sulu\\Bundle\\ContactBundle\\Entity\\Account', 'Sulu\\Component\\Security\\Authentication\\UserInterface' => 'Sulu\\Bundle\\SecurityBundle\\Entity\\User', 'Sulu\\Component\\Security\\Authentication\\RoleInterface' => 'Sulu\\Bundle\\SecurityBundle\\Entity\\Role', 'Sulu\\Component\\Security\\Authentication\\RoleSettingInterface' => 'Sulu\\Bundle\\SecurityBundle\\Entity\\RoleSetting', 'Sulu\\Component\\Security\\Authorization\\AccessControl\\AccessControlInterface' => 'Sulu\\Bundle\\SecurityBundle\\Entity\\AccessControl', 'Sulu\\Bundle\\TagBundle\\Tag\\TagInterface' => 'Sulu\\Bundle\\TagBundle\\Entity\\Tag', 'Sulu\\Bundle\\MediaBundle\\Entity\\MediaInterface' => 'Sulu\\Bundle\\MediaBundle\\Entity\\Media', 'Sulu\\Bundle\\CategoryBundle\\Entity\\CategoryInterface' => 'Sulu\\Bundle\\CategoryBundle\\Entity\\Category', 'Sulu\\Bundle\\CategoryBundle\\Entity\\CategoryMetaInterface' => 'Sulu\\Bundle\\CategoryBundle\\Entity\\CategoryMeta', 'Sulu\\Bundle\\CategoryBundle\\Entity\\CategoryTranslationInterface' => 'Sulu\\Bundle\\CategoryBundle\\Entity\\CategoryTranslation', 'Sulu\\Bundle\\CategoryBundle\\Entity\\KeywordInterface' => 'Sulu\\Bundle\\CategoryBundle\\Entity\\Keyword', 'Sulu\\Bundle\\RouteBundle\\Model\\RouteInterface' => 'Sulu\\Bundle\\RouteBundle\\Entity\\Route']);
    }
}
