<?php

namespace ContainerKp5Xx2P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluRoute_ContentTypeService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu_route.content_type' shared service.
     *
     * @return \Sulu\Bundle\RouteBundle\Content\Type\RouteContentType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_route.content_type'] = new \Sulu\Bundle\RouteBundle\Content\Type\RouteContentType();
    }
}
