<?php

namespace ContainerKp5Xx2P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluRoute_Manager_ConflictResolver_AutoIncrementService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_route.manager.conflict_resolver.auto_increment' shared service.
     *
     * @return \Sulu\Bundle\RouteBundle\Manager\AutoIncrementConflictResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_route.manager.conflict_resolver.auto_increment'] = new \Sulu\Bundle\RouteBundle\Manager\AutoIncrementConflictResolver(($container->services['sulu.repository.route'] ?? $container->getSulu_Repository_RouteService()));
    }
}
