<?php

namespace ContainerKp5Xx2P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluDocumentManager_Routing_VersionLoaderService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_document_manager.routing.version_loader' shared service.
     *
     * @return \Sulu\Bundle\DocumentManagerBundle\Routing\Loader\VersionRouteLoader
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_document_manager.routing.version_loader'] = new \Sulu\Bundle\DocumentManagerBundle\Routing\Loader\VersionRouteLoader(false);
    }
}
