<?php

namespace ContainerKp5Xx2P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluDocumentManager_Subscriber_Phpcr_RefreshService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_document_manager.subscriber.phpcr.refresh' shared service.
     *
     * @return \Sulu\Component\DocumentManager\Subscriber\Phpcr\RefreshSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_document_manager.subscriber.phpcr.refresh'] = new \Sulu\Component\DocumentManager\Subscriber\Phpcr\RefreshSubscriber(($container->privates['sulu_document_manager.event_dispatcher.standard'] ?? $container->getSuluDocumentManager_EventDispatcher_StandardService()), ($container->privates['sulu_document_manager.document_registry'] ?? ($container->privates['sulu_document_manager.document_registry'] = new \Sulu\Component\DocumentManager\DocumentRegistry('en'))));
    }
}
