<?php

namespace ContainerKp5Xx2P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluMedia_Doctrine_InvalidationListenerService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_media.doctrine.invalidation_listener' shared service.
     *
     * @return \Sulu\Bundle\MediaBundle\EventListener\CacheInvalidationListener
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_media.doctrine.invalidation_listener'] = new \Sulu\Bundle\MediaBundle\EventListener\CacheInvalidationListener(NULL);
    }
}
