<?php

namespace ContainerKp5Xx2P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluMedia_Fixtures_MediaTypesService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_media.fixtures.media_types' shared service.
     *
     * @return \Sulu\Bundle\MediaBundle\DataFixtures\ORM\LoadMediaTypes
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_media.fixtures.media_types'] = new \Sulu\Bundle\MediaBundle\DataFixtures\ORM\LoadMediaTypes();
    }
}
