<?php

namespace ContainerKp5Xx2P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSulu_Content_WebspaceStructureProviderService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu.content.webspace_structure_provider' shared service.
     *
     * @return \Sulu\Component\Webspace\StructureProvider\WebspaceStructureProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu.content.webspace_structure_provider'] = new \Sulu\Component\Webspace\StructureProvider\WebspaceStructureProvider(($container->services['.container.private.twig'] ?? $container->get_Container_Private_TwigService()), ($container->services['sulu.content.structure_manager'] ?? $container->getSulu_Content_StructureManagerService()), ($container->privates['sulu.content.webspace_structure_provider.cache'] ?? ($container->privates['sulu.content.webspace_structure_provider.cache'] = new \Doctrine\Common\Cache\FilesystemCache(($container->targetDir.''.'/sulu/webspace_structures')))));
    }
}
