<?php

namespace ContainerKp5Xx2P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluCore_DoctrineListBuilderFactoryService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu_core.doctrine_list_builder_factory' shared service.
     *
     * @return \Sulu\Component\Rest\ListBuilder\Doctrine\DoctrineListBuilderFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_core.doctrine_list_builder_factory'] = new \Sulu\Component\Rest\ListBuilder\Doctrine\DoctrineListBuilderFactory(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['sulu_core.list_builder_filter_type_registry'] ?? $container->load('getSuluCore_ListBuilderFilterTypeRegistryService')), ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()), $container->parameters['sulu_security.permissions'], ($container->privates['sulu_security.access_control_query_enhancer'] ?? $container->getSuluSecurity_AccessControlQueryEnhancerService()));
    }
}
