<?php

namespace ContainerKp5Xx2P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTwig_TemplateIteratorService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'twig.template_iterator' shared service.
     *
     * @return \Symfony\Bundle\TwigBundle\TemplateIterator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['twig.template_iterator'] = new \Symfony\Bundle\TwigBundle\TemplateIterator(($container->services['kernel'] ?? $container->get('kernel', 1)), ['/Users/pablolozano/Projects/SuluSchemaOrgBundle/vendor/symfony/twig-bridge/Resources/views/Email' => 'email', '/Users/pablolozano/Projects/SuluSchemaOrgBundle/vendor/symfony/twig-bridge/Resources/views/Form' => NULL], (\dirname(__DIR__, 5).'/templates'));
    }
}
