<?php
use Sulu\Component\Localization\Localization;
use Sulu\Component\Webspace\Manager\WebspaceCollection;
use Sulu\Component\Webspace\Portal;
use Sulu\Component\Webspace\PortalInformation;
use Sulu\Component\Webspace\Environment;
use Sulu\Component\Webspace\Security;
use Sulu\Component\Webspace\Segment;
use Sulu\Component\Webspace\Url;
use Sulu\Component\Webspace\CustomUrl;
use Sulu\Component\Webspace\Webspace;
use Sulu\Component\Webspace\Navigation;
use Sulu\Component\Webspace\NavigationContext;

/**
 * adminWebspaceCollectionCache
 *
 * DO NOT EDIT
 * This file is autogenerated by the Sulu Webspace component
 */
class adminWebspaceCollectionCache extends WebspaceCollection
{
    public function __construct()
    {
        $webspaceRefs = array();
        $portalRefs = array();
        $localizationRefs = array();
        $segmentRefs = array();
        $portalInformationRefs = array();

        // new webspace
        $webspace = new Webspace();
        $webspace->setKey('sulu-io');
        $webspace->setName('Sulu CMF');
        $security = new Security();
        $security->setSystem('Website');
        $security->setPermissionCheck(false);
        $webspace->setSecurity($security);
        // add localization to webspace
        $localization0 = new Localization();
        $localization0->setLanguage('en');
        $localization0->setCountry('');
        $localization0->setShadow('');
        $localization0->setDefault(true);
        $localization0->setXDefault('');
        $localizationRefs['sulu-io_en'] = $localization0;
        $webspace->addLocalization($localization0);
        // add theme
        $webspace->setTheme('default');


        $webspace->addTemplate('search', 'search/search');
        $webspace->addDefaultTemplate('homepage', 'default');
        $webspace->addDefaultTemplate('home', 'default');
        $webspace->addDefaultTemplate('page', 'default');

        // add navigation
        $navigation = new Navigation();
        $navigation->addContext(new NavigationContext('main',     array(
                        'title' =>     array(
                        'en' => 'Mainnavigation',
                )
,
                )
));
        $webspace->setNavigation($navigation);
        $webspace->setResourceLocatorStrategy('tree_leaf_edit');


        // new portal
        $portal = new Portal();
        $portal->setName('Sulu CMF');
        $portal->setKey('sulucmf');
        $portal->setWebspace($webspace);

        // add localization
        $localization = new Localization();
        $localization->setLanguage('en');
        $localization->setCountry('');
        $localization->setDefault('1');
        $localization->setXDefault('');
        $portal->addLocalization($localization);


        // add environment
        $environment = new Environment();
        $environment->setType('prod');

        // add environment url
        $url = new Url();
        $url->setUrl('{host}');
        $url->setLanguage('en');
        $url->setCountry('');
        $url->setSegment('');
        $url->setRedirect('');
        $url->setMain(true);
        $environment->addUrl($url);

        $portal->addEnvironment($environment);

        // add environment
        $environment = new Environment();
        $environment->setType('dev');

        // add environment url
        $url = new Url();
        $url->setUrl('{host}');
        $url->setLanguage('en');
        $url->setCountry('');
        $url->setSegment('');
        $url->setRedirect('');
        $url->setMain(true);
        $environment->addUrl($url);

        $portal->addEnvironment($environment);

        // add environment
        $environment = new Environment();
        $environment->setType('test');

        // add environment url
        $url = new Url();
        $url->setUrl('{host}');
        $url->setLanguage('en');
        $url->setCountry('');
        $url->setSegment('');
        $url->setRedirect('');
        $url->setMain(true);
        $environment->addUrl($url);

        $portal->addEnvironment($environment);
        $portalRefs['sulucmf'] = $portal;
        $webspace->addPortal($portal);

        $webspaceRefs['sulu-io'] = $webspace;



        $portalInformationRefs['prod']['{host}'] = new PortalInformation(
            1,
            $webspaceRefs['sulu-io'],
            $portalRefs['sulucmf'],
            $localizationRefs['sulu-io_en'],
            '{host}',
            null,
            null,
            true,
            '{host}',
            5
        );

        $portalInformationRefs['dev']['{host}'] = new PortalInformation(
            1,
            $webspaceRefs['sulu-io'],
            $portalRefs['sulucmf'],
            $localizationRefs['sulu-io_en'],
            '{host}',
            null,
            null,
            true,
            '{host}',
            5
        );

        $portalInformationRefs['test']['{host}'] = new PortalInformation(
            1,
            $webspaceRefs['sulu-io'],
            $portalRefs['sulucmf'],
            $localizationRefs['sulu-io_en'],
            '{host}',
            null,
            null,
            true,
            '{host}',
            5
        );


        $this->setWebspaces($webspaceRefs);
        $this->setPortals($portalRefs);
        $this->setPortalInformations($portalInformationRefs);
    }
}


