<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Container_Private_TwigService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the public '.container.private.twig' shared service.
     *
     * @return \Twig\Environment
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['.container.private.twig'] = $instance = new \Twig\Environment(($container->privates['twig.loader.native_filesystem'] ?? $container->load('getTwig_Loader_NativeFilesystemService')), ['autoescape' => 'name', 'cache' => ($container->targetDir.''.'/twig'), 'charset' => 'UTF-8', 'debug' => true, 'strict_variables' => true]);

        $instance->addExtension(($container->privates['twig.extension.security_csrf'] ?? ($container->privates['twig.extension.security_csrf'] = new \Symfony\Bridge\Twig\Extension\CsrfExtension())));
        $instance->addExtension(($container->privates['twig.extension.profiler'] ?? $container->load('getTwig_Extension_ProfilerService')));
        $instance->addExtension(($container->privates['twig.extension.trans'] ?? $container->load('getTwig_Extension_TransService')));
        $instance->addExtension(($container->privates['twig.extension.assets'] ?? $container->load('getTwig_Extension_AssetsService')));
        $instance->addExtension(($container->privates['twig.extension.code'] ?? $container->load('getTwig_Extension_CodeService')));
        $instance->addExtension(($container->privates['twig.extension.routing'] ?? $container->load('getTwig_Extension_RoutingService')));
        $instance->addExtension(($container->privates['twig.extension.yaml'] ?? ($container->privates['twig.extension.yaml'] = new \Symfony\Bridge\Twig\Extension\YamlExtension())));
        $instance->addExtension(($container->privates['twig.extension.expression'] ?? ($container->privates['twig.extension.expression'] = new \Symfony\Bridge\Twig\Extension\ExpressionExtension())));
        $instance->addExtension(($container->privates['twig.extension.httpkernel'] ?? ($container->privates['twig.extension.httpkernel'] = new \Symfony\Bridge\Twig\Extension\HttpKernelExtension())));
        $instance->addExtension(($container->privates['twig.extension.httpfoundation'] ?? $container->load('getTwig_Extension_HttpfoundationService')));
        $instance->addExtension(($container->privates['twig.extension.form'] ?? $container->load('getTwig_Extension_FormService')));
        $instance->addExtension(($container->privates['twig.extension.logout_url'] ?? $container->load('getTwig_Extension_LogoutUrlService')));
        $instance->addExtension(($container->privates['twig.extension.security'] ?? $container->load('getTwig_Extension_SecurityService')));
        $instance->addExtension(($container->privates['twig.extension.debug'] ?? ($container->privates['twig.extension.debug'] = new \Twig\Extension\DebugExtension())));
        $instance->addExtension(($container->privates['doctrine.twig.doctrine_extension'] ?? ($container->privates['doctrine.twig.doctrine_extension'] = new \Doctrine\Bundle\DoctrineBundle\Twig\DoctrineExtension())));
        $instance->addExtension(($container->privates['jms_serializer.twig_extension.serializer'] ?? ($container->privates['jms_serializer.twig_extension.serializer'] = new \JMS\Serializer\Twig\SerializerRuntimeExtension())));
        $instance->addExtension(($container->privates['sulu_page.export_twig_extension'] ?? $container->load('getSuluPage_ExportTwigExtensionService')));
        $instance->addExtension(($container->privates['sulu_contact.twig'] ?? $container->load('getSuluContact_TwigService')));
        $instance->addExtension(($container->privates['sulu_security.twig_extension.user'] ?? $container->load('getSuluSecurity_TwigExtension_UserService')));
        $instance->addExtension(($container->privates['sulu_website.twig.content_path'] ?? $container->load('getSuluWebsite_Twig_ContentPathService')));
        $instance->addExtension(($container->privates['sulu_website.twig.navigation.memoized'] ?? $container->load('getSuluWebsite_Twig_Navigation_MemoizedService')));
        $instance->addExtension(($container->privates['sulu_website.twig.sitemap.memoized'] ?? $container->load('getSuluWebsite_Twig_Sitemap_MemoizedService')));
        $instance->addExtension(($container->privates['sulu_website.twig.content.memoized'] ?? $container->load('getSuluWebsite_Twig_Content_MemoizedService')));
        $instance->addExtension(($container->privates['sulu_website.twig.meta'] ?? $container->load('getSuluWebsite_Twig_MetaService')));
        $instance->addExtension(($container->privates['sulu_website.twig.seo'] ?? $container->load('getSuluWebsite_Twig_SeoService')));
        $instance->addExtension(($container->privates['sulu_website.twig.util'] ?? ($container->privates['sulu_website.twig.util'] = new \Sulu\Bundle\WebsiteBundle\Twig\Core\UtilTwigExtension())));
        $instance->addExtension(($container->privates['sulu_tag.twig_extension'] ?? $container->load('getSuluTag_TwigExtensionService')));
        $instance->addExtension(($container->privates['sulu_media.twig_extension.disposition_type'] ?? ($container->privates['sulu_media.twig_extension.disposition_type'] = new \Sulu\Bundle\MediaBundle\Twig\DispositionTypeTwigExtension())));
        $instance->addExtension(($container->privates['sulu_media.twig_extension.media'] ?? $container->load('getSuluMedia_TwigExtension_MediaService')));
        $instance->addExtension(($container->privates['sulu_category.twig_extension'] ?? $container->load('getSuluCategory_TwigExtensionService')));
        $instance->addExtension(($container->privates['sulu_snippet.twig.snippet.memoized'] ?? $container->load('getSuluSnippet_Twig_Snippet_MemoizedService')));
        $instance->addExtension(($container->privates['sulu_snippet.twig.default_snippet'] ?? $container->load('getSuluSnippet_Twig_DefaultSnippetService')));
        $instance->addExtension(($container->privates['sulu_snippet.twig.area_snippet'] ?? $container->load('getSuluSnippet_Twig_AreaSnippetService')));
        $instance->addGlobal('app', ($container->privates['twig.app_variable'] ?? $container->load('getTwig_AppVariableService')));
        $instance->addRuntimeLoader(($container->privates['twig.runtime_loader'] ?? $container->load('getTwig_RuntimeLoaderService')));
        ($container->privates['twig.configurator.environment'] ?? $container->load('getTwig_Configurator_EnvironmentService'))->configure($instance);

        return $instance;
    }
}
