<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAssets_PackageSuluAdminService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'assets._package_sulu_admin' shared service.
     *
     * @return \Symfony\Component\Asset\PathPackage
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['assets._package_sulu_admin'] = new \Symfony\Component\Asset\PathPackage('', ($container->privates['assets._version_sulu_admin'] ?? ($container->privates['assets._version_sulu_admin'] = new \Symfony\Component\Asset\VersionStrategy\JsonManifestVersionStrategy((\dirname(__DIR__, 5).'/public/build/admin/manifest.json')))), ($container->privates['assets.context'] ?? $container->load('getAssets_ContextService')));
    }
}
