<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrinePhpcr_Admin_LiveSessionService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the public 'doctrine_phpcr.admin.live_session' shared service.
     *
     * @return \Jackalope\Session
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['doctrine_phpcr.admin.live_session'] = ($container->privates['doctrine_phpcr.admin.jackalope.repository.live'] ?? $container->load('getDoctrinePhpcr_Admin_Jackalope_Repository_LiveService'))->login(($container->privates['doctrine_phpcr.admin.live_credentials'] ?? ($container->privates['doctrine_phpcr.admin.live_credentials'] = new \PHPCR\SimpleCredentials($container->getEnv('PHPCR_USERNAME'), $container->getEnv('PHPCR_PASSWORD')))), NULL);
    }
}
