<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrine_Orm_Listeners_ResolveTargetEntityService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'doctrine.orm.listeners.resolve_target_entity' shared service.
     *
     * @return \Doctrine\ORM\Tools\ResolveTargetEntityListener
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['doctrine.orm.listeners.resolve_target_entity'] = $instance = new \Doctrine\ORM\Tools\ResolveTargetEntityListener();

        $instance->addResolveTargetEntity('Sulu\\Bundle\\MediaBundle\\Entity\\CollectionInterface', 'Sulu\\Bundle\\MediaBundle\\Entity\\Collection', []);
        $instance->addResolveTargetEntity('Sulu\\Bundle\\ContactBundle\\Entity\\AccountInterface', 'Sulu\\Bundle\\ContactBundle\\Entity\\Account', []);
        $instance->addResolveTargetEntity('Sulu\\Bundle\\ContactBundle\\Entity\\ContactInterface', 'Sulu\\Bundle\\ContactBundle\\Entity\\Contact', []);
        $instance->addResolveTargetEntity('Sulu\\Bundle\\ContactBundle\\Entity\\AccountInterface', 'Sulu\\Bundle\\ContactBundle\\Entity\\Account', []);
        $instance->addResolveTargetEntity('Sulu\\Component\\Security\\Authentication\\UserInterface', 'Sulu\\Bundle\\SecurityBundle\\Entity\\User', []);
        $instance->addResolveTargetEntity('Sulu\\Component\\Security\\Authentication\\RoleInterface', 'Sulu\\Bundle\\SecurityBundle\\Entity\\Role', []);
        $instance->addResolveTargetEntity('Sulu\\Component\\Security\\Authentication\\RoleSettingInterface', 'Sulu\\Bundle\\SecurityBundle\\Entity\\RoleSetting', []);
        $instance->addResolveTargetEntity('Sulu\\Component\\Security\\Authorization\\AccessControl\\AccessControlInterface', 'Sulu\\Bundle\\SecurityBundle\\Entity\\AccessControl', []);
        $instance->addResolveTargetEntity('Sulu\\Bundle\\TagBundle\\Tag\\TagInterface', 'Sulu\\Bundle\\TagBundle\\Entity\\Tag', []);
        $instance->addResolveTargetEntity('Sulu\\Bundle\\MediaBundle\\Entity\\MediaInterface', 'Sulu\\Bundle\\MediaBundle\\Entity\\Media', []);
        $instance->addResolveTargetEntity('Sulu\\Bundle\\CategoryBundle\\Entity\\CategoryInterface', 'Sulu\\Bundle\\CategoryBundle\\Entity\\Category', []);
        $instance->addResolveTargetEntity('Sulu\\Bundle\\CategoryBundle\\Entity\\CategoryMetaInterface', 'Sulu\\Bundle\\CategoryBundle\\Entity\\CategoryMeta', []);
        $instance->addResolveTargetEntity('Sulu\\Bundle\\CategoryBundle\\Entity\\CategoryTranslationInterface', 'Sulu\\Bundle\\CategoryBundle\\Entity\\CategoryTranslation', []);
        $instance->addResolveTargetEntity('Sulu\\Bundle\\CategoryBundle\\Entity\\KeywordInterface', 'Sulu\\Bundle\\CategoryBundle\\Entity\\Keyword', []);
        $instance->addResolveTargetEntity('Sulu\\Bundle\\RouteBundle\\Model\\RouteInterface', 'Sulu\\Bundle\\RouteBundle\\Entity\\Route', []);

        return $instance;
    }
}
