<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFosJsRouting_SerializerService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the public 'fos_js_routing.serializer' shared service.
     *
     * @return \Symfony\Component\Serializer\Serializer
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['fos_js_routing.serializer'] = new \Symfony\Component\Serializer\Serializer([0 => ($container->privates['fos_js_routing.normalizer.route_collection'] ?? ($container->privates['fos_js_routing.normalizer.route_collection'] = new \FOS\JsRoutingBundle\Serializer\Normalizer\RouteCollectionNormalizer())), 1 => ($container->privates['fos_js_routing.normalizer.routes_response'] ?? ($container->privates['fos_js_routing.normalizer.routes_response'] = new \FOS\JsRoutingBundle\Serializer\Normalizer\RoutesResponseNormalizer())), 2 => ($container->privates['fos_js_routing.denormalizer.route_collection'] ?? ($container->privates['fos_js_routing.denormalizer.route_collection'] = new \FOS\JsRoutingBundle\Serializer\Denormalizer\RouteCollectionDenormalizer()))], ['json' => ($container->privates['fos_js_routing.encoder'] ?? ($container->privates['fos_js_routing.encoder'] = new \Symfony\Component\Serializer\Encoder\JsonEncoder()))]);
    }
}
