<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFragment_Renderer_HincludeService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'fragment.renderer.hinclude' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Fragment\HIncludeFragmentRenderer
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['fragment.renderer.hinclude'] = $instance = new \Symfony\Component\HttpKernel\Fragment\HIncludeFragmentRenderer(($container->services['.container.private.twig'] ?? $container->load('get_Container_Private_TwigService')), ($container->privates['uri_signer'] ?? ($container->privates['uri_signer'] = new \Symfony\Component\HttpKernel\UriSigner('secret'))), NULL);

        $instance->setFragmentPath('/admin/_fragments');

        return $instance;
    }
}
