<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHandcraftedinthealpsRestRouting_Inflector_DoctrineService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'handcraftedinthealps_rest_routing.inflector.doctrine' shared service.
     *
     * @return \HandcraftedInTheAlps\RestRoutingBundle\Inflector\DoctrineInflector
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['handcraftedinthealps_rest_routing.inflector.doctrine'] = new \HandcraftedInTheAlps\RestRoutingBundle\Inflector\DoctrineInflector();
    }
}
