<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHandcraftedinthealpsRestRouting_Loader_Reader_ControllerService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'handcraftedinthealps_rest_routing.loader.reader.controller' shared service.
     *
     * @return \HandcraftedInTheAlps\RestRoutingBundle\Routing\Loader\Reader\RestControllerReader
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['handcraftedinthealps_rest_routing.loader.reader.controller'] = new \HandcraftedInTheAlps\RestRoutingBundle\Routing\Loader\Reader\RestControllerReader(($container->privates['handcraftedinthealps_rest_routing.loader.reader.action'] ?? $container->load('getHandcraftedinthealpsRestRouting_Loader_Reader_ActionService')), ($container->privates['annotations.cached_reader'] ?? $container->getAnnotations_CachedReaderService()));
    }
}
