<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMassiveSearch_LocalizationDecoratorService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'massive_search.localization_decorator' shared service.
     *
     * @return \Massive\Bundle\SearchBundle\Search\Decorator\LocalizationDecorator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['massive_search.localization_decorator'] = new \Massive\Bundle\SearchBundle\Search\Decorator\LocalizationDecorator(($container->privates['massive_search.index_name_decorator'] ?? $container->load('getMassiveSearch_IndexNameDecoratorService')));
    }
}
