<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMassiveSearch_Metadata_FactoryService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'massive_search.metadata.factory' shared service.
     *
     * @return \Metadata\MetadataFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['massive_search.metadata.factory'] = $instance = new \Metadata\MetadataFactory(($container->privates['massive_search.metadata.driver.chain'] ?? $container->load('getMassiveSearch_Metadata_Driver_ChainService')), 'Metadata\\ClassHierarchyMetadata', true);

        $instance->setCache(($container->privates['massive_search.metadata.cache.file_cache'] ?? ($container->privates['massive_search.metadata.cache.file_cache'] = new \Metadata\Cache\FileCache(($container->targetDir.''.'/massive-search')))));

        return $instance;
    }
}
