<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMassiveSearch_Command_ReindexService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'massive_search.command.reindex' shared service.
     *
     * @return \Massive\Bundle\SearchBundle\Command\ReindexCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['massive_search.command.reindex'] = $instance = new \Massive\Bundle\SearchBundle\Command\ReindexCommand(($container->privates['massive_search.reindex.resume_manager'] ?? ($container->privates['massive_search.reindex.resume_manager'] = new \Massive\Bundle\SearchBundle\Search\Reindex\ResumeManager())), ($container->services['massive_search.search_manager'] ?? $container->load('getMassiveSearch_SearchManagerService')), ($container->privates['massive_search.reindex.provider_registry'] ?? $container->load('getMassiveSearch_Reindex_ProviderRegistryService')), 'test');

        $instance->setName('massive:search:reindex');

        return $instance;
    }
}
