<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMassiveSearch_ObjectToDocumentConverterService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'massive_search.object_to_document_converter' shared service.
     *
     * @return \Massive\Bundle\SearchBundle\Search\ObjectToDocumentConverter
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['massive_search.converter'] ?? $container->load('getMassiveSearch_ConverterService'));

        if (isset($container->privates['massive_search.object_to_document_converter'])) {
            return $container->privates['massive_search.object_to_document_converter'];
        }

        return $container->privates['massive_search.object_to_document_converter'] = new \Massive\Bundle\SearchBundle\Search\ObjectToDocumentConverter(($container->privates['sulu_search.search.factory'] ?? ($container->privates['sulu_search.search.factory'] = new \Sulu\Bundle\SearchBundle\Search\Factory())), ($container->privates['massive_search.metadata.field_evaluator'] ?? $container->load('getMassiveSearch_Metadata_FieldEvaluatorService')), $a);
    }
}
