<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMassiveBuild_Build_RegistryService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'massive_build.build.registry' shared service.
     *
     * @return \Massive\Bundle\BuildBundle\Build\BuildRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['massive_build.build.registry'] = $instance = new \Massive\Bundle\BuildBundle\Build\BuildRegistry();

        $instance->addBuilder(($container->privates['sulu_core.build.builder.database'] ?? ($container->privates['sulu_core.build.builder.database'] = new \Sulu\Bundle\CoreBundle\Build\DatabaseBuilder())));
        $instance->addBuilder(($container->privates['sulu_core.build.builder.phpcr'] ?? ($container->privates['sulu_core.build.builder.phpcr'] = new \Sulu\Bundle\CoreBundle\Build\PhpcrBuilder())));
        $instance->addBuilder(($container->privates['sulu_core.build.builder.phpcr_migrations'] ?? $container->load('getSuluCore_Build_Builder_PhpcrMigrationsService')));
        $instance->addBuilder(($container->privates['sulu_core.build.builder.fixtures'] ?? ($container->privates['sulu_core.build.builder.fixtures'] = new \Sulu\Bundle\CoreBundle\Build\FixturesBuilder())));
        $instance->addBuilder(($container->privates['sulu_search.build.index'] ?? ($container->privates['sulu_search.build.index'] = new \Sulu\Bundle\SearchBundle\Build\IndexBuilder())));
        $instance->addBuilder(($container->privates['sulu_core.build.builder.node_order'] ?? $container->load('getSuluCore_Build_Builder_NodeOrderService')));
        $instance->addBuilder(($container->privates['sulu_security.build.user'] ?? ($container->privates['sulu_security.build.user'] = new \Sulu\Bundle\SecurityBundle\Build\UserBuilder())));
        $instance->addBuilder(($container->privates['sulu_security.build.security'] ?? ($container->privates['sulu_security.build.security'] = new \Sulu\Bundle\SecurityBundle\Build\SecurityBuilder())));
        $instance->addBuilder(($container->privates['sulu_media.system_collections.builder'] ?? ($container->privates['sulu_media.system_collections.builder'] = new \Sulu\Component\Media\SystemCollections\SystemCollectionBuilder())));
        $instance->addBuilder(($container->privates['massive_build.builder.virtual.prod'] ?? $container->load('getMassiveBuild_Builder_Virtual_ProdService')));
        $instance->addBuilder(($container->privates['massive_build.builder.virtual.dev'] ?? $container->load('getMassiveBuild_Builder_Virtual_DevService')));
        $instance->addBuilder(($container->privates['massive_build.builder.virtual.maintain'] ?? ($container->privates['massive_build.builder.virtual.maintain'] = new \Massive\Bundle\BuildBundle\Builder\VirtualBuilder('maintain', [0 => 'node_order', 1 => 'search_index', 2 => 'phpcr_migrations']))));

        return $instance;
    }
}
