<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPhpcrMigrations_VersionFinderService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'phpcr_migrations.version_finder' shared service.
     *
     * @return \PHPCR\Migrations\VersionFinder
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['phpcr_migrations.version_finder'] = new \PHPCR\Migrations\VersionFinder($container->parameters['phpcr_migrations.paths']);
    }
}
