<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPhpcrMigrations_Command_StatusService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the public 'phpcr_migrations.command.status' shared service.
     *
     * @return \DTL\Bundle\PhpcrMigrations\Command\StatusCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['phpcr_migrations.command.status'] = new \DTL\Bundle\PhpcrMigrations\Command\StatusCommand(($container->privates['phpcr_migrations.version_storage'] ?? $container->load('getPhpcrMigrations_VersionStorageService')), ($container->privates['phpcr_migrations.version_finder'] ?? $container->load('getPhpcrMigrations_VersionFinderService')));
    }
}
