<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPhpcrMigrations_Command_InitializeService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the public 'phpcr_migrations.command.initialize' shared service.
     *
     * @return \DTL\Bundle\PhpcrMigrations\Command\InitializeCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['phpcr_migrations.command.initialize'] = new \DTL\Bundle\PhpcrMigrations\Command\InitializeCommand(($container->privates['phpcr_migrations.migrator_factory'] ?? $container->load('getPhpcrMigrations_MigratorFactoryService')));
    }
}
