<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluRoute_Command_UpdateRouteService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_route.command.update_route' shared service.
     *
     * @return \Sulu\Bundle\RouteBundle\Command\UpdateRouteCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['sulu_route.command.update_route'] = $instance = new \Sulu\Bundle\RouteBundle\Command\UpdateRouteCommand(($container->services['translator'] ?? $container->getTranslatorService()), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['sulu_route.manager.route_manager'] ?? $container->load('getSuluRoute_Manager_RouteManagerService')));

        $instance->setName('sulu:route:update');

        return $instance;
    }
}
