<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluCustomUrls_UrlProviderService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_custom_urls.url_provider' shared service.
     *
     * @return \Sulu\Component\CustomUrl\WebspaceCustomUrlProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_custom_urls.url_provider'] = new \Sulu\Component\CustomUrl\WebspaceCustomUrlProvider(($container->services['sulu_custom_urls.manager'] ?? $container->load('getSuluCustomUrls_ManagerService')));
    }
}
