<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluWebsite_Twig_Sitemap_MemoizedService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_website.twig.sitemap.memoized' shared service.
     *
     * @return \Sulu\Bundle\WebsiteBundle\Twig\Sitemap\MemoizedSitemapTwigExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_website.twig.sitemap.memoized'] = new \Sulu\Bundle\WebsiteBundle\Twig\Sitemap\MemoizedSitemapTwigExtension(($container->privates['sulu_website.twig.sitemap'] ?? $container->load('getSuluWebsite_Twig_SitemapService')), ($container->privates['sulu_core.cache.memoize'] ?? $container->load('getSuluCore_Cache_MemoizeService')), 1);
    }
}
