<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluCore_Rest_ViewHandler_CsvService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_core.rest.view_handler.csv' shared service.
     *
     * @return \Sulu\Component\Rest\Csv\CsvHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_core.rest.view_handler.csv'] = new \Sulu\Component\Rest\Csv\CsvHandler(($container->services['sulu_core.array_serializer'] ?? $container->load('getSuluCore_ArraySerializerService')));
    }
}
