<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_Preview_DefaultsProviderService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_page.preview.defaults_provider' shared service.
     *
     * @return \Sulu\Bundle\PageBundle\Preview\PageRouteDefaultsProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_page.preview.defaults_provider'] = new \Sulu\Bundle\PageBundle\Preview\PageRouteDefaultsProvider(($container->services['sulu_page.structure.factory'] ?? $container->getSuluPage_Structure_FactoryService()), ($container->services['sulu_document_manager.document_inspector'] ?? $container->getSuluDocumentManager_DocumentInspectorService()), ($container->services['sulu.content.structure_manager'] ?? $container->getSulu_Content_StructureManagerService()));
    }
}
