<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluAdmin_ViewBuilderFactoryService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_admin.view_builder_factory' shared service.
     *
     * @return \Sulu\Bundle\AdminBundle\Admin\View\ViewBuilderFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_admin.view_builder_factory'] = new \Sulu\Bundle\AdminBundle\Admin\View\ViewBuilderFactory();
    }
}
