<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_PagesSitemapProviderService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_page.pages_sitemap_provider' shared service.
     *
     * @return \Sulu\Bundle\PageBundle\Sitemap\PagesSitemapProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_page.pages_sitemap_provider'] = new \Sulu\Bundle\PageBundle\Sitemap\PagesSitemapProvider(($container->services['sulu_page.content_repository'] ?? $container->getSuluPage_ContentRepositoryService()), ($container->services['sulu_core.webspace.webspace_manager'] ?? $container->getSuluCore_Webspace_WebspaceManagerService()), 'test', ($container->privates['sulu_security.access_control_manager'] ?? $container->getSuluSecurity_AccessControlManagerService()));
    }
}
