<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluCore_Build_Builder_PhpcrService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_core.build.builder.phpcr' shared service.
     *
     * @return \Sulu\Bundle\CoreBundle\Build\PhpcrBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_core.build.builder.phpcr'] = new \Sulu\Bundle\CoreBundle\Build\PhpcrBuilder();
    }
}
