<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluDocumentManager_LiveSessionService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the public 'sulu_document_manager.live_session' shared service.
     *
     * @return \Sulu\Bundle\DocumentManagerBundle\Session\Session
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_document_manager.live_session'] = new \Sulu\Bundle\DocumentManagerBundle\Session\Session(($container->privates['sulu_document_manager.decorated_live_session.inner'] ?? $container->load('getSuluDocumentManager_DecoratedLiveSession_InnerService')));
    }
}
