<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluAdmin_DownloadBuildCommandService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_admin.download_build_command' shared service.
     *
     * @return \Sulu\Bundle\AdminBundle\Command\DownloadBuildCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['sulu_admin.download_build_command'] = $instance = new \Sulu\Bundle\AdminBundle\Command\DownloadBuildCommand();

        $instance->setName('sulu:admin:download-build');

        return $instance;
    }
}
