<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_Document_Serializer_Subscriber_ExtensionContainerService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_page.document.serializer.subscriber.extension_container' shared service.
     *
     * @return \Sulu\Bundle\PageBundle\Serializer\Subscriber\ExtensionContainerSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_page.document.serializer.subscriber.extension_container'] = new \Sulu\Bundle\PageBundle\Serializer\Subscriber\ExtensionContainerSubscriber();
    }
}
