<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluWebsite_NavigationMapperService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_website.navigation_mapper' shared service.
     *
     * @return \Sulu\Bundle\WebsiteBundle\Navigation\NavigationMapper
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_website.navigation_mapper'] = new \Sulu\Bundle\WebsiteBundle\Navigation\NavigationMapper(($container->services['sulu.content.mapper'] ?? $container->load('getSulu_Content_MapperService')), ($container->privates['sulu.content.query_executor'] ?? $container->load('getSulu_Content_QueryExecutorService')), ($container->privates['sulu_website.navigation_mapper.query_builder'] ?? $container->load('getSuluWebsite_NavigationMapper_QueryBuilderService')), ($container->services['sulu.phpcr.session'] ?? $container->getSulu_Phpcr_SessionService()), NULL, $container->parameters['sulu_security.permissions']);
    }
}
