<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_Extension_ExcerptService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_page.extension.excerpt' shared service.
     *
     * @return \Sulu\Bundle\PageBundle\Content\Structure\ExcerptStructureExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_page.extension.excerpt'] = new \Sulu\Bundle\PageBundle\Content\Structure\ExcerptStructureExtension(($container->services['sulu.content.structure_manager'] ?? $container->getSulu_Content_StructureManagerService()), ($container->services['sulu.content.type_manager'] ?? $container->getSulu_Content_TypeManagerService()), ($container->privates['sulu_page.export.manager'] ?? $container->load('getSuluPage_Export_ManagerService')), ($container->privates['sulu_page.import.manager'] ?? $container->load('getSuluPage_Import_ManagerService')), ($container->privates['sulu_search.search.factory'] ?? ($container->privates['sulu_search.search.factory'] = new \Sulu\Bundle\SearchBundle\Search\Factory())));
    }
}
