<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSulu_Content_MapperService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the public 'sulu.content.mapper' shared service.
     *
     * @return \Sulu\Component\Content\Mapper\ContentMapper
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu.content.mapper'] = new \Sulu\Component\Content\Mapper\ContentMapper(($container->services['sulu_document_manager.document_manager'] ?? $container->getSuluDocumentManager_DocumentManagerService()), ($container->services['sulu_core.webspace.webspace_manager'] ?? $container->getSuluCore_Webspace_WebspaceManagerService()), ($container->services['.container.private.form.factory'] ?? $container->load('get_Container_Private_Form_FactoryService')), ($container->services['sulu_document_manager.document_inspector'] ?? $container->getSuluDocumentManager_DocumentInspectorService()), ($container->services['sulu_document_manager.property_encoder'] ?? $container->getSuluDocumentManager_PropertyEncoderService()), ($container->services['sulu.content.structure_manager'] ?? $container->getSulu_Content_StructureManagerService()), ($container->services['sulu_page.extension.manager'] ?? $container->load('getSuluPage_Extension_ManagerService')), ($container->services['sulu.content.type_manager'] ?? $container->getSulu_Content_TypeManagerService()), ($container->services['sulu.phpcr.session'] ?? $container->getSulu_Phpcr_SessionService()), ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()), ($container->privates['sulu.content.resource_locator.strategy_pool'] ?? $container->load('getSulu_Content_ResourceLocator_StrategyPoolService')), ($container->privates['sulu_document_manager.namespace_registry'] ?? $container->getSuluDocumentManager_NamespaceRegistryService()), ($container->privates['sulu_security.access_control_manager'] ?? $container->getSuluSecurity_AccessControlManagerService()), $container->parameters['sulu_security.permissions'], ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));
    }
}
