<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSulu_Content_ResourceLocator_Strategy_TreeGeneratorService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu.content.resource_locator.strategy.tree_generator' shared service.
     *
     * @return \Sulu\Component\Content\Types\ResourceLocator\Strategy\TreeGenerator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu.content.resource_locator.strategy.tree_generator'] = new \Sulu\Component\Content\Types\ResourceLocator\Strategy\TreeGenerator();
    }
}
