<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_WebspaceLocalizationControllerService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the public 'sulu_page.webspace_localization_controller' shared service.
     *
     * @return \Sulu\Bundle\PageBundle\Controller\WebspaceLocalizationController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_page.webspace_localization_controller'] = new \Sulu\Bundle\PageBundle\Controller\WebspaceLocalizationController(($container->services['fos_rest.view_handler'] ?? $container->load('getFosRest_ViewHandlerService')), ($container->services['sulu_core.webspace.webspace_manager'] ?? $container->getSuluCore_Webspace_WebspaceManagerService()));
    }
}
