<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluContact_Content_SingleContactSelectionService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the public 'sulu_contact.content.single_contact_selection' shared service.
     *
     * @return \Sulu\Bundle\ContactBundle\Content\Types\SingleContactSelection
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_contact.content.single_contact_selection'] = new \Sulu\Bundle\ContactBundle\Content\Types\SingleContactSelection(($container->services['sulu.repository.contact'] ?? $container->load('getSulu_Repository_ContactService')), ($container->privates['sulu_contact.reference_store.contact'] ?? ($container->privates['sulu_contact.reference_store.contact'] = new \Sulu\Bundle\WebsiteBundle\ReferenceStore\ReferenceStore())));
    }
}
