<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluTag_Search_TagsConverterService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_tag.search.tags_converter' shared service.
     *
     * @return \Sulu\Bundle\TagBundle\Search\TagsConverter
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_tag.search.tags_converter'] = new \Sulu\Bundle\TagBundle\Search\TagsConverter(($container->services['sulu_tag.tag_manager'] ?? $container->getSuluTag_TagManagerService()));
    }
}
