<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluCore_ArraySerializerService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the public 'sulu_core.array_serializer' shared service.
     *
     * @return \Sulu\Component\Serializer\ArraySerializer
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_core.array_serializer'] = new \Sulu\Component\Serializer\ArraySerializer(($container->services['jms_serializer'] ?? $container->load('getJmsSerializerService')));
    }
}
