<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSecurity_RoleControllerService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the public 'sulu_security.role_controller' shared service.
     *
     * @return \Sulu\Bundle\SecurityBundle\Controller\RoleController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_security.role_controller'] = new \Sulu\Bundle\SecurityBundle\Controller\RoleController(($container->services['fos_rest.view_handler'] ?? $container->load('getFosRest_ViewHandlerService')), ($container->services['sulu_core.list_builder.field_descriptor_factory'] ?? $container->load('getSuluCore_ListBuilder_FieldDescriptorFactoryService')), ($container->services['sulu_core.doctrine_rest_helper'] ?? $container->load('getSuluCore_DoctrineRestHelperService')), ($container->services['sulu_core.doctrine_list_builder_factory'] ?? $container->load('getSuluCore_DoctrineListBuilderFactoryService')), ($container->services['sulu_security.mask_converter'] ?? $container->getSuluSecurity_MaskConverterService()), ($container->services['sulu.repository.role'] ?? $container->getSulu_Repository_RoleService()), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), 'Sulu\\Bundle\\SecurityBundle\\Entity\\Role');
    }
}
