<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPreview_Preview_RendererService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_preview.preview.renderer' shared service.
     *
     * @return \Sulu\Bundle\PreviewBundle\Preview\Renderer\PreviewRenderer
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_preview.preview.renderer'] = new \Sulu\Bundle\PreviewBundle\Preview\Renderer\PreviewRenderer(($container->privates['sulu_route.routing.defaults_provider'] ?? $container->load('getSuluRoute_Routing_DefaultsProviderService')), ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($container->privates['sulu_preview.preview.kernel_factory'] ?? ($container->privates['sulu_preview.preview.kernel_factory'] = new \Sulu\Bundle\PreviewBundle\Preview\Renderer\WebsiteKernelFactory())), ($container->services['sulu_core.webspace.webspace_manager'] ?? $container->getSuluCore_Webspace_WebspaceManagerService()), ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()), [], 'test', (($container->hasParameter("sulu_audience_targeting.headers.target_group")) ? ($container->getParameter("sulu_audience_targeting.headers.target_group")) : (null)));
    }
}
