<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluContact_ContactControllerService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the public 'sulu_contact.contact_controller' shared service.
     *
     * @return \Sulu\Bundle\ContactBundle\Controller\ContactController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_contact.contact_controller'] = new \Sulu\Bundle\ContactBundle\Controller\ContactController(($container->services['fos_rest.view_handler'] ?? $container->load('getFosRest_ViewHandlerService')), ($container->services['security.token_storage'] ?? $container->getSecurity_TokenStorageService()), ($container->services['sulu_core.doctrine_rest_helper'] ?? $container->load('getSuluCore_DoctrineRestHelperService')), ($container->services['sulu_core.list_builder.field_descriptor_factory'] ?? $container->load('getSuluCore_ListBuilder_FieldDescriptorFactoryService')), ($container->services['sulu_core.doctrine_list_builder_factory'] ?? $container->load('getSuluCore_DoctrineListBuilderFactoryService')), ($container->services['sulu_contact.contact_manager'] ?? $container->load('getSuluContact_ContactManagerService')), ($container->services['sulu.repository.contact'] ?? $container->load('getSulu_Repository_ContactService')), ($container->services['sulu_media.media_manager'] ?? $container->getSuluMedia_MediaManagerService()), ($container->services['sulu.repository.user'] ?? $container->getSulu_Repository_UserService()), ($container->services['sulu_contact.util.index_comparator'] ?? ($container->services['sulu_contact.util.index_comparator'] = new \Sulu\Bundle\ContactBundle\Util\IndexComparator())), 'Sulu\\Bundle\\ContactBundle\\Entity\\Contact', 'Sulu');
    }
}
