<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSecurity_GroupRepositoryService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_security.group_repository' shared service.
     *
     * @return \Sulu\Bundle\SecurityBundle\Entity\GroupRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_security.group_repository'] = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService())->getRepository('SuluSecurityBundle:Group');
    }
}
