<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_Export_ManagerService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_page.export.manager' shared service.
     *
     * @return \Sulu\Component\Export\Manager\ExportManager
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['sulu_page.export.manager'] = $instance = new \Sulu\Component\Export\Manager\ExportManager(($container->services['sulu.content.type_manager'] ?? $container->getSulu_Content_TypeManagerService()));

        $instance->add('number', '1.2.xliff', ['translate' => true]);
        $instance->add('text_line', '1.2.xliff', ['translate' => true]);
        $instance->add('text_area', '1.2.xliff', ['translate' => true]);
        $instance->add('text_editor', '1.2.xliff', ['translate' => true]);
        $instance->add('resource_locator', '1.2.xliff', ['translate' => false]);
        $instance->add('block', '1.2.xliff', ['translate' => false]);
        $instance->add('smart_content', '1.2.xliff', ['translate' => false]);
        $instance->add('teaser_selection', '1.2.xliff', ['translate' => false]);
        $instance->add('page_selection', '1.2.xliff', ['translate' => false]);
        $instance->add('single_page_selection', '1.2.xliff', ['translate' => false]);
        $instance->add('phone', '1.2.xliff', ['translate' => false]);
        $instance->add('password', '1.2.xliff', ['translate' => false]);
        $instance->add('url', '1.2.xliff', ['translate' => false]);
        $instance->add('email', '1.2.xliff', ['translate' => false]);
        $instance->add('date', '1.2.xliff', ['translate' => false]);
        $instance->add('datetime', '1.2.xliff', ['translate' => false]);
        $instance->add('time', '1.2.xliff', ['translate' => false]);
        $instance->add('color', '1.2.xliff', ['translate' => false]);
        $instance->add('checkbox', '1.2.xliff', ['translate' => false]);
        $instance->add('select', '1.2.xliff', ['translate' => false]);
        $instance->add('single_select', '1.2.xliff', ['translate' => false]);
        $instance->add('contact_account_selection', '1.2.xliff', ['translate' => false]);
        $instance->add('single_contact_selection', '1.2.xliff', ['translate' => false]);
        $instance->add('contact_selection', '1.2.xliff', ['translate' => false]);
        $instance->add('single_account_selection', '1.2.xliff', ['translate' => false]);
        $instance->add('account_selection', '1.2.xliff', ['translate' => false]);
        $instance->add('tag_selection', '1.2.xliff', ['translate' => false]);
        $instance->add('media_selection', '1.2.xliff', ['translate' => false]);
        $instance->add('single_media_selection', '1.2.xliff', ['translate' => false]);
        $instance->add('image_map', '1.2.xliff', ['translate' => false]);
        $instance->add('category_selection', '1.2.xliff', ['translate' => false]);
        $instance->add('single_category_selection', '1.2.xliff', ['translate' => false]);
        $instance->add('single_snippet_selection', '1.2.xliff', ['translate' => false]);
        $instance->add('snippet_selection', '1.2.xliff', ['translate' => false]);
        $instance->add('location', '1.2.xliff', ['translate' => false]);
        $instance->add('route', '1.2.xliff', ['translate' => false]);
        $instance->add('page_tree_route', '1.2.xliff', ['translate' => false]);

        return $instance;
    }
}
