<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluCategory_TwigExtensionService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_category.twig_extension' shared service.
     *
     * @return \Sulu\Bundle\CategoryBundle\Twig\CategoryTwigExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_category.twig_extension'] = new \Sulu\Bundle\CategoryBundle\Twig\CategoryTwigExtension(($container->services['sulu_category.category_manager'] ?? $container->load('getSuluCategory_CategoryManagerService')), ($container->privates['sulu_category.category_request_handler'] ?? $container->load('getSuluCategory_CategoryRequestHandlerService')), ($container->services['sulu_core.array_serializer'] ?? $container->load('getSuluCore_ArraySerializerService')), ($container->privates['sulu_core.cache.memoize'] ?? $container->load('getSuluCore_Cache_MemoizeService')));
    }
}
