<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluRoute_Generator_ExpressionTokenProviderService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_route.generator.expression_token_provider' shared service.
     *
     * @return \Sulu\Bundle\RouteBundle\Generator\SymfonyExpressionTokenProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_route.generator.expression_token_provider'] = new \Sulu\Bundle\RouteBundle\Generator\SymfonyExpressionTokenProvider(($container->services['translator'] ?? $container->getTranslatorService()));
    }
}
