<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluMedia_FileVersionMetaRepositoryService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_media.file_version_meta_repository' shared service.
     *
     * @return \Sulu\Bundle\MediaBundle\Entity\FileVersionMetaRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_media.file_version_meta_repository'] = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService())->getRepository('SuluMediaBundle:FileVersionMeta');
    }
}
