<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_PageResourceLocatorControllerService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the public 'sulu_page.page_resource_locator_controller' shared service.
     *
     * @return \Sulu\Bundle\PageBundle\Controller\PageResourcelocatorController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_page.page_resource_locator_controller'] = new \Sulu\Bundle\PageBundle\Controller\PageResourcelocatorController(($container->services['fos_rest.view_handler'] ?? $container->load('getFosRest_ViewHandlerService')), ($container->services['sulu_page.rl_repository'] ?? $container->load('getSuluPage_RlRepositoryService')), ($container->services['sulu_document_manager.document_manager'] ?? $container->getSuluDocumentManager_DocumentManagerService()));
    }
}
