<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSwiftmailer_Mailer_Default_Spool_MemoryService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'swiftmailer.mailer.default.spool.memory' shared service.
     *
     * @return \Swift_MemorySpool
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['swiftmailer.mailer.default.spool.memory'] = new \Swift_MemorySpool();
    }
}
