<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSnippet_Controller_SnippetService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the public 'sulu_snippet.controller.snippet' shared service.
     *
     * @return \Sulu\Bundle\SnippetBundle\Controller\SnippetController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_snippet.controller.snippet'] = new \Sulu\Bundle\SnippetBundle\Controller\SnippetController(($container->services['fos_rest.view_handler'] ?? $container->load('getFosRest_ViewHandlerService')), ($container->services['sulu.content.mapper'] ?? $container->load('getSulu_Content_MapperService')), ($container->services['sulu.content.structure_manager'] ?? $container->getSulu_Content_StructureManagerService()), ($container->services['sulu_snippet.repository'] ?? $container->load('getSuluSnippet_RepositoryService')), ($container->services['security.token_storage'] ?? $container->getSecurity_TokenStorageService()), ($container->services['router'] ?? $container->getRouterService()), ($container->services['sulu_snippet.default_snippet.manager'] ?? $container->load('getSuluSnippet_DefaultSnippet_ManagerService')), ($container->services['sulu_document_manager.document_manager'] ?? $container->getSuluDocumentManager_DocumentManagerService()), ($container->services['.container.private.form.factory'] ?? $container->load('get_Container_Private_Form_FactoryService')), ($container->services['sulu_hash.request_hash_checker'] ?? $container->load('getSuluHash_RequestHashCheckerService')), ($container->services['sulu_core.list_rest_helper'] ?? $container->load('getSuluCore_ListRestHelperService')), ($container->services['sulu_document_manager.metadata_factory.base'] ?? $container->getSuluDocumentManager_MetadataFactory_BaseService()), ($container->services['translator'] ?? $container->getTranslatorService()));
    }
}
