<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluAdmin_XmlListMetadataLoaderService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_admin.xml_list_metadata_loader' shared service.
     *
     * @return \Sulu\Bundle\AdminBundle\Metadata\ListMetadata\XmlListMetadataLoader
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_admin.xml_list_metadata_loader'] = new \Sulu\Bundle\AdminBundle\Metadata\ListMetadata\XmlListMetadataLoader(($container->services['sulu_core.list_builder.field_descriptor_factory'] ?? $container->load('getSuluCore_ListBuilder_FieldDescriptorFactoryService')), ($container->services['translator'] ?? $container->getTranslatorService()));
    }
}
