<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluContact_PositionRepositoryService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_contact.position_repository' shared service.
     *
     * @return \Sulu\Bundle\ContactBundle\Entity\PositionRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_contact.position_repository'] = ($container->services['doctrine'] ?? $container->load('getDoctrineService'))->getRepository('SuluContactBundle:Position');
    }
}
