<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSecurity_SystemLanguageSelectHelperService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the public 'sulu_security.system_language_select_helper' shared service.
     *
     * @return \Sulu\Bundle\SecurityBundle\Admin\Helper\SystemLanguageSelect
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_security.system_language_select_helper'] = new \Sulu\Bundle\SecurityBundle\Admin\Helper\SystemLanguageSelect($container->parameters['sulu_core.translated_locales']);
    }
}
