<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluMedia_MediaListRepresentationFactoryService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_media.media_list_representation_factory' shared service.
     *
     * @return \Sulu\Bundle\MediaBundle\Media\ListRepresentationFactory\MediaListRepresentationFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_media.media_list_representation_factory'] = new \Sulu\Bundle\MediaBundle\Media\ListRepresentationFactory\MediaListRepresentationFactory(($container->services['sulu_media.media_manager'] ?? $container->getSuluMedia_MediaManagerService()), ($container->services['sulu_media.format_manager'] ?? $container->getSuluMedia_FormatManagerService()));
    }
}
