<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSnippet_Content_SnippetService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the public 'sulu_snippet.content.snippet' shared service.
     *
     * @return \Sulu\Bundle\SnippetBundle\Content\SnippetContent
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_snippet.content.snippet'] = new \Sulu\Bundle\SnippetBundle\Content\SnippetContent(($container->services['sulu_snippet.default_snippet.manager'] ?? $container->load('getSuluSnippet_DefaultSnippet_ManagerService')), ($container->services['sulu_snippet.resolver'] ?? $container->load('getSuluSnippet_ResolverService')), ($container->services['sulu_snippet.reference_store.snippet'] ?? ($container->services['sulu_snippet.reference_store.snippet'] = new \Sulu\Bundle\WebsiteBundle\ReferenceStore\ReferenceStore())), true);
    }
}
