<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluCore_Webspace_SettingsManagerService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_core.webspace.settings_manager' shared service.
     *
     * @return \Sulu\Component\Webspace\Settings\SettingsManager
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_core.webspace.settings_manager'] = new \Sulu\Component\Webspace\Settings\SettingsManager(($container->privates['sulu_document_manager.session_manager'] ?? $container->load('getSuluDocumentManager_SessionManagerService')), ($container->services['sulu.phpcr.session'] ?? $container->getSulu_Phpcr_SessionService()));
    }
}
