<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluCore_Cache_Memoize_CacheService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_core.cache.memoize.cache' shared service.
     *
     * @return \Doctrine\Common\Cache\ArrayCache
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_core.cache.memoize.cache'] = new \Doctrine\Common\Cache\ArrayCache();
    }
}
