<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluMedia_Command_ClearCacheService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_media.command.clear_cache' shared service.
     *
     * @return \Sulu\Bundle\MediaBundle\Command\ClearCacheCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['sulu_media.command.clear_cache'] = $instance = new \Sulu\Bundle\MediaBundle\Command\ClearCacheCommand(($container->privates['sulu_media.format_cache_clearer'] ?? $container->load('getSuluMedia_FormatCacheClearerService')));

        $instance->setName('sulu:media:format:cache:clear');

        return $instance;
    }
}
