<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluMedia_CollectionControllerService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the public 'sulu_media.collection_controller' shared service.
     *
     * @return \Sulu\Bundle\MediaBundle\Controller\CollectionController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_media.collection_controller'] = new \Sulu\Bundle\MediaBundle\Controller\CollectionController(($container->services['fos_rest.view_handler'] ?? $container->load('getFosRest_ViewHandlerService')), ($container->services['security.token_storage'] ?? $container->getSecurity_TokenStorageService()), ($container->services['sulu_core.list_rest_helper'] ?? $container->load('getSuluCore_ListRestHelperService')), ($container->services['sulu_security.security_checker'] ?? $container->getSuluSecurity_SecurityCheckerService()), ($container->services['translator'] ?? $container->getTranslatorService()), ($container->services['sulu_media.system_collections.manager'] ?? $container->load('getSuluMedia_SystemCollections_ManagerService')), ($container->services['sulu_media.collection_manager'] ?? $container->load('getSuluMedia_CollectionManagerService')), $container->parameters['sulu_media.collection.type.default'], $container->parameters['sulu_security.permissions'], 'Sulu\\Bundle\\MediaBundle\\Entity\\Collection');
    }
}
