<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSnippet_SnippetAreaControllerService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the public 'sulu_snippet.snippet_area_controller' shared service.
     *
     * @return \Sulu\Bundle\SnippetBundle\Controller\SnippetAreaController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_snippet.snippet_area_controller'] = new \Sulu\Bundle\SnippetBundle\Controller\SnippetAreaController(($container->services['sulu_snippet.default_snippet.manager'] ?? $container->load('getSuluSnippet_DefaultSnippet_ManagerService')), ($container->services['sulu_document_manager.document_manager'] ?? $container->getSuluDocumentManager_DocumentManagerService()), ($container->services['sulu_security.security_checker'] ?? $container->getSuluSecurity_SecurityCheckerService()), ($container->services['security.token_storage'] ?? $container->getSecurity_TokenStorageService()), []);
    }
}
