<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSnippet_Twig_Snippet_MemoizedService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_snippet.twig.snippet.memoized' shared service.
     *
     * @return \Sulu\Bundle\SnippetBundle\Twig\MemoizedSnippetTwigExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_snippet.twig.snippet.memoized'] = new \Sulu\Bundle\SnippetBundle\Twig\MemoizedSnippetTwigExtension(($container->privates['sulu_snippet.twig.snippet'] ?? $container->load('getSuluSnippet_Twig_SnippetService')), ($container->privates['sulu_core.cache.memoize'] ?? $container->load('getSuluCore_Cache_MemoizeService')), 1);
    }
}
