<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluCore_SymfonyExpressionLanguageProviderService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_core.symfony_expression_language_provider' shared service.
     *
     * @return \Sulu\Bundle\CoreBundle\ExpressionLanguage\ContainerExpressionLanguageProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_core.symfony_expression_language_provider'] = new \Sulu\Bundle\CoreBundle\ExpressionLanguage\ContainerExpressionLanguageProvider($container);
    }
}
