<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPreview_Preview_KernelFactoryService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_preview.preview.kernel_factory' shared service.
     *
     * @return \Sulu\Bundle\PreviewBundle\Preview\Renderer\WebsiteKernelFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_preview.preview.kernel_factory'] = new \Sulu\Bundle\PreviewBundle\Preview\Renderer\WebsiteKernelFactory();
    }
}
