<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluContact_SmartContent_DataProvider_ContactService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_contact.smart_content.data_provider.contact' shared service.
     *
     * @return \Sulu\Component\Contact\SmartContent\ContactDataProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_contact.smart_content.data_provider.contact'] = new \Sulu\Component\Contact\SmartContent\ContactDataProvider(($container->services['sulu_contact.contact_manager'] ?? $container->load('getSuluContact_ContactManagerService')), ($container->services['sulu_core.array_serializer'] ?? $container->load('getSuluCore_ArraySerializerService')), ($container->privates['sulu_contact.reference_store.contact'] ?? ($container->privates['sulu_contact.reference_store.contact'] = new \Sulu\Bundle\WebsiteBundle\ReferenceStore\ReferenceStore())));
    }
}
