<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluCore_Webspace_UrlProviderService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_core.webspace.url_provider' shared service.
     *
     * @return \Sulu\Component\Webspace\Url\WebspaceUrlChainProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_core.webspace.url_provider'] = new \Sulu\Component\Webspace\Url\WebspaceUrlChainProvider([0 => ($container->privates['sulu_core.webspace.url_provider.default'] ?? ($container->privates['sulu_core.webspace.url_provider.default'] = new \Sulu\Component\Webspace\Url\WebspaceUrlProvider())), 1 => ($container->privates['sulu_custom_urls.url_provider'] ?? $container->load('getSuluCustomUrls_UrlProviderService'))]);
    }
}
