<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluAdmin_ListMetadataProviderService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_admin.list_metadata_provider' shared service.
     *
     * @return \Sulu\Bundle\AdminBundle\Metadata\ListMetadata\ListMetadataProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_admin.list_metadata_provider'] = new \Sulu\Bundle\AdminBundle\Metadata\ListMetadata\ListMetadataProvider(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['sulu_admin.xml_list_metadata_loader'] ?? $container->load('getSuluAdmin_XmlListMetadataLoaderService'));
        }, 1));
    }
}
