<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPreview_CacheCommandSubscriberService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_preview.cache_command_subscriber' shared service.
     *
     * @return \Sulu\Bundle\PreviewBundle\EventSubscriber\CacheCommandSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_preview.cache_command_subscriber'] = new \Sulu\Bundle\PreviewBundle\EventSubscriber\CacheCommandSubscriber(($container->privates['sulu_preview.preview.kernel_factory'] ?? ($container->privates['sulu_preview.preview.kernel_factory'] = new \Sulu\Bundle\PreviewBundle\Preview\Renderer\WebsiteKernelFactory())), 'test');
    }
}
