<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluAdmin_ViewRegistryService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_admin.view_registry' shared service.
     *
     * @return \Sulu\Bundle\AdminBundle\Admin\View\ViewRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_admin.view_registry'] = new \Sulu\Bundle\AdminBundle\Admin\View\ViewRegistry(($container->services['sulu_admin.admin_pool'] ?? $container->load('getSuluAdmin_AdminPoolService')));
    }
}
