<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSearch_IndexConfigurationProviderService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_search.index_configuration_provider' shared service.
     *
     * @return \Sulu\Bundle\SearchBundle\Search\Configuration\IndexConfigurationProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_search.index_configuration_provider'] = new \Sulu\Bundle\SearchBundle\Search\Configuration\IndexConfigurationProvider(($container->services['translator'] ?? $container->getTranslatorService()), $container->parameters['sulu_search.indexes']);
    }
}
