<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluWebsite_Command_DumpSitemapService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_website.command.dump_sitemap' shared service.
     *
     * @return \Sulu\Bundle\WebsiteBundle\Command\DumpSitemapCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['sulu_website.command.dump_sitemap'] = $instance = new \Sulu\Bundle\WebsiteBundle\Command\DumpSitemapCommand(($container->services['sulu_core.webspace.webspace_manager'] ?? $container->getSuluCore_Webspace_WebspaceManagerService()), ($container->privates['sulu_website.sitemap.xml_dumper'] ?? $container->load('getSuluWebsite_Sitemap_XmlDumperService')), ($container->services['.container.private.filesystem'] ?? ($container->services['.container.private.filesystem'] = new \Symfony\Component\Filesystem\Filesystem())), ($container->targetDir.''.'/sulu/sitemaps'), 'test', 'http', 'localhost');

        $instance->setName('sulu:website:dump-sitemap');

        return $instance;
    }
}
