<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSecurity_LastLoginListenerService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_security.last_login_listener' shared service.
     *
     * @return \Sulu\Bundle\SecurityBundle\EventListener\LastLoginListener
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_security.last_login_listener'] = new \Sulu\Bundle\SecurityBundle\EventListener\LastLoginListener(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));
    }
}
