<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSnippet_LanguageControllerService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the public 'sulu_snippet.language_controller' shared service.
     *
     * @return \Sulu\Bundle\SnippetBundle\Controller\LanguageController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_snippet.language_controller'] = new \Sulu\Bundle\SnippetBundle\Controller\LanguageController(($container->services['sulu_core.webspace.webspace_manager'] ?? $container->getSuluCore_Webspace_WebspaceManagerService()));
    }
}
