<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_Teaser_Serializer_EventSubscriberService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_page.teaser.serializer.event_subscriber' shared service.
     *
     * @return \Sulu\Bundle\PageBundle\EventListener\TeaserSerializeEventSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_page.teaser.serializer.event_subscriber'] = new \Sulu\Bundle\PageBundle\EventListener\TeaserSerializeEventSubscriber(($container->services['sulu_media.media_manager'] ?? $container->getSuluMedia_MediaManagerService()));
    }
}
