<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluMedia_FieldMetadataValidator_ImageMapService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_media.field_metadata_validator.image_map' shared service.
     *
     * @return \Sulu\Bundle\MediaBundle\Metadata\ImageMapFieldMetadataValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_media.field_metadata_validator.image_map'] = new \Sulu\Bundle\MediaBundle\Metadata\ImageMapFieldMetadataValidator();
    }
}
