<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluContact_PositionControllerService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the public 'sulu_contact.position_controller' shared service.
     *
     * @return \Sulu\Bundle\ContactBundle\Controller\PositionController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_contact.position_controller'] = new \Sulu\Bundle\ContactBundle\Controller\PositionController(($container->services['fos_rest.view_handler'] ?? $container->load('getFosRest_ViewHandlerService')), ($container->privates['sulu_contact.position_repository'] ?? $container->load('getSuluContact_PositionRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));
    }
}
