<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluCore_RepresentationHandlerService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_core.representation_handler' shared service.
     *
     * @return \Sulu\Component\Serializer\RepresentationSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_core.representation_handler'] = new \Sulu\Component\Serializer\RepresentationSubscriber();
    }
}
