<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_Export_WebspaceService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the public 'sulu_page.export.webspace' shared service.
     *
     * @return \Sulu\Component\Content\Export\WebspaceExport
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_page.export.webspace'] = new \Sulu\Component\Content\Export\WebspaceExport(($container->services['.container.private.twig'] ?? $container->load('get_Container_Private_TwigService')), ($container->services['sulu_document_manager.document_manager'] ?? $container->getSuluDocumentManager_DocumentManagerService()), ($container->services['sulu_document_manager.document_inspector'] ?? $container->getSuluDocumentManager_DocumentInspectorService()), ($container->services['sulu.content.structure_manager'] ?? $container->getSulu_Content_StructureManagerService()), ($container->services['sulu_page.extension.manager'] ?? $container->load('getSuluPage_Extension_ManagerService')), ($container->privates['sulu_page.export.manager'] ?? $container->load('getSuluPage_Export_ManagerService')), $container->parameters['sulu_page.export.webspace.formats']);
    }
}
