<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluCore_BooleanFilterTypeService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_core.boolean_filter_type' shared service.
     *
     * @return \Sulu\Component\Rest\ListBuilder\Filter\BooleanFilterType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_core.boolean_filter_type'] = new \Sulu\Component\Rest\ListBuilder\Filter\BooleanFilterType();
    }
}
