<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluAdmin_FieldTypeOptionRegistryService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_admin.field_type_option_registry' shared service.
     *
     * @return \Sulu\Bundle\AdminBundle\FieldType\FieldTypeOptionRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['sulu_admin.field_type_option_registry'] = $instance = new \Sulu\Bundle\AdminBundle\FieldType\FieldTypeOptionRegistry();

        $instance->add('single_snippet_selection', 'single_selection', ['default_type' => 'list_overlay', 'resource_key' => 'snippets', 'view' => ['name' => 'sulu_snippet.edit_form', 'result_to_view' => ['id' => 'id']], 'types' => ['list_overlay' => ['adapter' => 'table', 'list_key' => 'snippets', 'display_properties' => [0 => 'title'], 'icon' => 'su-snippet', 'empty_text' => 'sulu_snippet.no_snippet_selected', 'overlay_title' => 'sulu_snippet.single_snippet_selection_overlay_title', 'detail_options' => []]]]);
        $instance->add('single_category_selection', 'single_selection', ['default_type' => 'list_overlay', 'resource_key' => 'categories', 'view' => ['name' => 'sulu_category.edit_form', 'result_to_view' => ['id' => 'id']], 'types' => ['list_overlay' => ['adapter' => 'tree_table_slim', 'list_key' => 'categories', 'display_properties' => [0 => 'name'], 'empty_text' => 'sulu_category.no_category_selected', 'icon' => 'fa-tags', 'overlay_title' => 'sulu_category.single_category_selection_overlay_title', 'detail_options' => []]]]);
        $instance->add('single_account_selection', 'single_selection', ['default_type' => 'auto_complete', 'resource_key' => 'accounts', 'types' => ['auto_complete' => ['display_property' => 'name', 'search_properties' => [0 => 'number', 1 => 'name']], 'list_overlay' => ['adapter' => 'table', 'list_key' => 'accounts', 'display_properties' => [0 => 'name'], 'empty_text' => 'sulu_contact.no_account_selected', 'icon' => 'su-house', 'overlay_title' => 'sulu_contact.single_account_selection_overlay_title', 'detail_options' => []]]]);
        $instance->add('single_contact_selection', 'single_selection', ['default_type' => 'list_overlay', 'resource_key' => 'contacts', 'view' => ['name' => 'sulu_contact.contact_edit_form', 'result_to_view' => ['id' => 'id']], 'types' => ['auto_complete' => ['display_property' => 'fullName', 'search_properties' => [0 => 'fullName']], 'list_overlay' => ['adapter' => 'table', 'list_key' => 'contacts', 'display_properties' => [0 => 'fullName'], 'empty_text' => 'sulu_contact.no_contact_selected', 'icon' => 'su-user', 'overlay_title' => 'sulu_contact.single_contact_selection_overlay_title', 'detail_options' => []]]]);
        $instance->add('single_contact_title_selection', 'single_selection', ['default_type' => 'single_select', 'resource_key' => 'contact_titles', 'types' => ['single_select' => ['id_property' => 'id', 'display_property' => 'title', 'overlay_title' => 'sulu_contact.edit_title_overlay_title']]]);
        $instance->add('single_contact_position_selection', 'single_selection', ['default_type' => 'single_select', 'resource_key' => 'contact_positions', 'types' => ['single_select' => ['id_property' => 'id', 'display_property' => 'position', 'overlay_title' => 'sulu_contact.edit_position_overlay_title']]]);
        $instance->add('single_page_selection', 'single_selection', ['default_type' => 'list_overlay', 'resource_key' => 'pages', 'view' => ['name' => 'sulu_page.page_edit_form', 'result_to_view' => ['id' => 'id', 'webspace' => 'webspace']], 'types' => ['list_overlay' => ['adapter' => 'column_list', 'detail_options' => ['ghost-content' => true], 'list_key' => 'pages', 'display_properties' => [0 => 'title'], 'empty_text' => 'sulu_page.no_page_selected', 'icon' => 'su-document', 'overlay_title' => 'sulu_page.single_selection_overlay_title']]]);
        $instance->add('snippet_selection', 'selection', ['default_type' => 'list_overlay', 'resource_key' => 'snippets', 'view' => ['name' => 'sulu_snippet.edit_form', 'result_to_view' => ['id' => 'id']], 'types' => ['list_overlay' => ['adapter' => 'table', 'list_key' => 'snippets', 'display_properties' => [0 => 'title'], 'icon' => 'su-snippet', 'label' => 'sulu_snippet.selection_label', 'overlay_title' => 'sulu_snippet.selection_overlay_title']]]);
        $instance->add('category_selection', 'selection', ['default_type' => 'list', 'resource_key' => 'categories', 'types' => ['list' => ['adapter' => 'tree_table_slim', 'list_key' => 'categories']]]);
        $instance->add('tag_selection', 'selection', ['default_type' => 'auto_complete', 'resource_key' => 'tags', 'types' => ['auto_complete' => ['allow_add' => true, 'display_property' => 'name', 'id_property' => 'name', 'filter_parameter' => 'names', 'search_properties' => [0 => 'name']]]]);
        $instance->add('contact_selection', 'selection', ['default_type' => 'list_overlay', 'resource_key' => 'contacts', 'types' => ['list_overlay' => ['adapter' => 'table', 'list_key' => 'contacts', 'display_properties' => [0 => 'firstName', 1 => 'lastName'], 'icon' => 'su-user', 'label' => 'sulu_contact.contact_selection_label', 'overlay_title' => 'sulu_contact.contact_selection_overlay_title']]]);
        $instance->add('account_selection', 'selection', ['default_type' => 'list_overlay', 'resource_key' => 'accounts', 'types' => ['list_overlay' => ['adapter' => 'table', 'list_key' => 'accounts', 'display_properties' => [0 => 'name'], 'icon' => 'su-user', 'label' => 'sulu_contact.account_selection_label', 'overlay_title' => 'sulu_contact.account_selection_overlay_title']]]);
        $instance->add('page_selection', 'selection', ['default_type' => 'list_overlay', 'resource_key' => 'pages', 'view' => ['name' => 'sulu_page.page_edit_form', 'result_to_view' => ['id' => 'id', 'webspaceKey' => 'webspace']], 'types' => ['list_overlay' => ['adapter' => 'column_list', 'list_key' => 'pages', 'display_properties' => [0 => 'title', 1 => 'url'], 'icon' => 'su-document', 'label' => 'sulu_page.selection_label', 'overlay_title' => 'sulu_page.selection_overlay_title']]]);

        return $instance;
    }
}
