<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSulu_Content_Type_PageSelectionService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the public 'sulu.content.type.page_selection' shared service.
     *
     * @return \Sulu\Bundle\PageBundle\Content\Types\PageSelection
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu.content.type.page_selection'] = new \Sulu\Bundle\PageBundle\Content\Types\PageSelection(($container->privates['sulu.content.query_executor'] ?? $container->load('getSulu_Content_QueryExecutorService')), ($container->privates['sulu_page.smart_content.data_provider.content.query_builder'] ?? $container->load('getSuluPage_SmartContent_DataProvider_Content_QueryBuilderService')), ($container->privates['sulu_page.reference_store.content'] ?? ($container->privates['sulu_page.reference_store.content'] = new \Sulu\Bundle\WebsiteBundle\ReferenceStore\ReferenceStore())), true, $container->parameters['sulu_security.permissions']);
    }
}
