<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluCategory_Content_Type_SingleCategorySelectionService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the public 'sulu_category.content.type.single_category_selection' shared service.
     *
     * @return \Sulu\Bundle\CategoryBundle\Content\Types\SingleCategorySelection
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_category.content.type.single_category_selection'] = new \Sulu\Bundle\CategoryBundle\Content\Types\SingleCategorySelection(($container->services['sulu_category.category_manager'] ?? $container->load('getSuluCategory_CategoryManagerService')));
    }
}
