<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluWebsite_Sitemap_QueryBuilderService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_website.sitemap.query_builder' shared service.
     *
     * @return \Sulu\Bundle\WebsiteBundle\Sitemap\SitemapContentQueryBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_website.sitemap.query_builder'] = new \Sulu\Bundle\WebsiteBundle\Sitemap\SitemapContentQueryBuilder(($container->services['sulu.content.structure_manager'] ?? $container->getSulu_Content_StructureManagerService()), ($container->services['sulu_page.extension.manager'] ?? $container->load('getSuluPage_Extension_ManagerService')), 'i18n');
    }
}
