<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluDocumentManager_Command_FixturesLoadService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_document_manager.command.fixtures_load' shared service.
     *
     * @return \Sulu\Bundle\DocumentManagerBundle\Command\FixturesLoadCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['sulu_document_manager.command.fixtures_load'] = $instance = new \Sulu\Bundle\DocumentManagerBundle\Command\FixturesLoadCommand(($container->privates['sulu_document_manager.data_fixtures.executor'] ?? $container->load('getSuluDocumentManager_DataFixtures_ExecutorService')), new RewindableGenerator(function () use ($container) {
            return new \EmptyIterator();
        }, 0));

        $instance->setName('sulu:document:fixtures:load');

        return $instance;
    }
}
