<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_Webspace_Serializer_EventSubscriberService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_page.webspace.serializer.event_subscriber' shared service.
     *
     * @return \Sulu\Bundle\PageBundle\EventListener\WebspaceSerializeEventSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_page.webspace.serializer.event_subscriber'] = new \Sulu\Bundle\PageBundle\EventListener\WebspaceSerializeEventSubscriber(($container->services['sulu_core.webspace.webspace_manager'] ?? $container->getSuluCore_Webspace_WebspaceManagerService()), ($container->privates['sulu_core.webspace.url_provider'] ?? $container->load('getSuluCore_Webspace_UrlProviderService')), ($container->privates['sulu.content.resource_locator.strategy_pool'] ?? $container->load('getSulu_Content_ResourceLocator_StrategyPoolService')), ($container->privates['sulu_security.access_control_manager'] ?? $container->getSuluSecurity_AccessControlManagerService()), ($container->services['security.token_storage'] ?? $container->getSecurity_TokenStorageService()), 'test');
    }
}
