<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSearch_Search_FactoryService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_search.search.factory' shared service.
     *
     * @return \Sulu\Bundle\SearchBundle\Search\Factory
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_search.search.factory'] = new \Sulu\Bundle\SearchBundle\Search\Factory();
    }
}
