<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluDocumentManager_DecoratedLiveSession_InnerService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_document_manager.decorated_live_session.inner' shared service.
     *
     * @return \Jackalope\Session
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_document_manager.decorated_live_session.inner'] = ($container->privates['doctrine_phpcr.jackalope.repository.live'] ?? $container->load('getDoctrinePhpcr_Jackalope_Repository_LiveService'))->login(($container->privates['doctrine_phpcr.live_credentials'] ?? ($container->privates['doctrine_phpcr.live_credentials'] = new \PHPCR\SimpleCredentials($container->getEnv('PHPCR_USERNAME'), $container->getEnv('PHPCR_PASSWORD')))), $container->getEnv('string:PHPCR_WORKSPACE').'_live');
    }
}
