<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluAdmin_StructureFormMetadataLoaderService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_admin.structure_form_metadata_loader' shared service.
     *
     * @return \Sulu\Bundle\AdminBundle\Metadata\FormMetadata\StructureFormMetadataLoader
     */
    public static function do($container, $lazyLoad = true)
    {
        if ($lazyLoad) {
            return $container->privates['sulu_admin.structure_form_metadata_loader'] = $container->createProxy('StructureFormMetadataLoader_d440bd8', function () use ($container) {
                return \StructureFormMetadataLoader_d440bd8::staticProxyConstructor(function (&$wrappedInstance, \ProxyManager\Proxy\LazyLoadingInterface $proxy) use ($container) {
                    $wrappedInstance = self::do($container, false);

                    $proxy->setProxyInitializer(null);

                    return true;
                });
            });
        }

        return new \Sulu\Bundle\AdminBundle\Metadata\FormMetadata\StructureFormMetadataLoader(($container->services['sulu_page.structure.factory'] ?? $container->getSuluPage_Structure_FactoryService()), ($container->privates['sulu_admin.form_metadata.form_metadata_mapper'] ?? ($container->privates['sulu_admin.form_metadata.form_metadata_mapper'] = new \Sulu\Bundle\AdminBundle\FormMetadata\FormMetadataMapper())), ($container->services['sulu_core.webspace.webspace_manager'] ?? $container->getSuluCore_Webspace_WebspaceManagerService()), ($container->privates['sulu_admin.field_metadata_validator.chain'] ?? $container->load('getSuluAdmin_FieldMetadataValidator_ChainService')), $container->parameters['sulu.content.structure.default_types'], $container->parameters['sulu_core.locales'], ($container->targetDir.''.'/sulu/form-structures'), true);
    }
}
