<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_Command_WebspaceImportService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_page.command.webspace_import' shared service.
     *
     * @return \Sulu\Bundle\PageBundle\Command\WebspaceImportCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['sulu_page.command.webspace_import'] = $instance = new \Sulu\Bundle\PageBundle\Command\WebspaceImportCommand(($container->services['sulu_page.import.webspace'] ?? $container->load('getSuluPage_Import_WebspaceService')), ($container->privates['logger'] ?? ($container->privates['logger'] = new \Symfony\Component\HttpKernel\Log\Logger())));

        $instance->setName('sulu:webspaces:import');

        return $instance;
    }
}
