<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_SmartContent_ContentTypeService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the public 'sulu_page.smart_content.content_type' shared service.
     *
     * @return \Sulu\Component\SmartContent\ContentType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_page.smart_content.content_type'] = new \Sulu\Component\SmartContent\ContentType(($container->services['sulu_page.smart_content.data_provider_pool'] ?? $container->load('getSuluPage_SmartContent_DataProviderPoolService')), ($container->services['sulu_tag.tag_manager'] ?? $container->getSuluTag_TagManagerService()), ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($container->privates['sulu_tag.tag_request_handler'] ?? $container->load('getSuluTag_TagRequestHandlerService')), ($container->privates['sulu_category.category_request_handler'] ?? $container->load('getSuluCategory_CategoryRequestHandlerService')), ($container->privates['sulu_tag.reference_store.tag'] ?? ($container->privates['sulu_tag.reference_store.tag'] = new \Sulu\Bundle\WebsiteBundle\ReferenceStore\ReferenceStore())), ($container->privates['sulu_category.reference_store.category'] ?? ($container->privates['sulu_category.reference_store.category'] = new \Sulu\Bundle\WebsiteBundle\ReferenceStore\ReferenceStore())), NULL, ($container->services['sulu_core.webspace.request_analyzer'] ?? $container->getSuluCore_Webspace_RequestAnalyzerService()));
    }
}
