<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSulu_Content_ResourceLocator_StrategyPoolService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu.content.resource_locator.strategy_pool' shared service.
     *
     * @return \Sulu\Component\Content\Types\ResourceLocator\Strategy\ResourceLocatorStrategyPool
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu.content.resource_locator.strategy_pool'] = new \Sulu\Component\Content\Types\ResourceLocator\Strategy\ResourceLocatorStrategyPool(['tree_leaf_edit' => ($container->privates['sulu.content.resource_locator.strategy.tree_leaf_edit'] ?? $container->load('getSulu_Content_ResourceLocator_Strategy_TreeLeafEditService')), 'tree_full_edit' => ($container->privates['sulu.content.resource_locator.strategy.tree_full_edit'] ?? $container->load('getSulu_Content_ResourceLocator_Strategy_TreeFullEditService'))], ($container->services['sulu_core.webspace.webspace_manager'] ?? $container->getSuluCore_Webspace_WebspaceManagerService()));
    }
}
