<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestUserProviderService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the public 'test_user_provider' shared service.
     *
     * @return \Sulu\Bundle\TestBundle\Testing\TestUserProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['test_user_provider'] = new \Sulu\Bundle\TestBundle\Testing\TestUserProvider(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->services['sulu.repository.contact'] ?? $container->load('getSulu_Repository_ContactService')), ($container->services['sulu.repository.user'] ?? $container->getSulu_Repository_UserService()), ($container->services['sulu_security.encoder_factory'] ?? $container->load('getSuluSecurity_EncoderFactoryService')), ($container->privates['sulu_security.user_provider'] ?? $container->load('getSuluSecurity_UserProviderService')));
    }
}
