<?php

namespace ContainerItPaVCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTwig_Loader_NativeFilesystemService extends TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelTestDebugContainer
{
    /**
     * Gets the private 'twig.loader.native_filesystem' shared service.
     *
     * @return \Twig\Loader\FilesystemLoader
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['twig.loader.native_filesystem'] = $instance = new \Twig\Loader\FilesystemLoader([], \dirname(__DIR__, 5));

        $instance->addPath('/Users/pablolozano/Projects/SuluSchemaOrgBundle/vendor/doctrine/doctrine-bundle/Resources/views', 'Doctrine');
        $instance->addPath('/Users/pablolozano/Projects/SuluSchemaOrgBundle/vendor/doctrine/doctrine-bundle/Resources/views', '!Doctrine');
        $instance->addPath('/Users/pablolozano/Projects/SuluSchemaOrgBundle/vendor/doctrine/phpcr-bundle/src/Resources/views', 'DoctrinePHPCR');
        $instance->addPath('/Users/pablolozano/Projects/SuluSchemaOrgBundle/vendor/doctrine/phpcr-bundle/src/Resources/views', '!DoctrinePHPCR');
        $instance->addPath('/Users/pablolozano/Projects/SuluSchemaOrgBundle/vendor/symfony/swiftmailer-bundle/Resources/views', 'Swiftmailer');
        $instance->addPath('/Users/pablolozano/Projects/SuluSchemaOrgBundle/vendor/symfony/swiftmailer-bundle/Resources/views', '!Swiftmailer');
        $instance->addPath('/Users/pablolozano/Projects/SuluSchemaOrgBundle/vendor/sulu/sulu/src/Sulu/Bundle/PageBundle/Resources/views', 'SuluPage');
        $instance->addPath('/Users/pablolozano/Projects/SuluSchemaOrgBundle/vendor/sulu/sulu/src/Sulu/Bundle/PageBundle/Resources/views', '!SuluPage');
        $instance->addPath('/Users/pablolozano/Projects/SuluSchemaOrgBundle/vendor/sulu/sulu/src/Sulu/Bundle/SecurityBundle/Resources/views', 'SuluSecurity');
        $instance->addPath('/Users/pablolozano/Projects/SuluSchemaOrgBundle/vendor/sulu/sulu/src/Sulu/Bundle/SecurityBundle/Resources/views', '!SuluSecurity');
        $instance->addPath('/Users/pablolozano/Projects/SuluSchemaOrgBundle/vendor/sulu/sulu/src/Sulu/Bundle/WebsiteBundle/Resources/views', 'SuluWebsite');
        $instance->addPath('/Users/pablolozano/Projects/SuluSchemaOrgBundle/vendor/sulu/sulu/src/Sulu/Bundle/WebsiteBundle/Resources/views', '!SuluWebsite');
        $instance->addPath('/Users/pablolozano/Projects/SuluSchemaOrgBundle/vendor/sulu/sulu/src/Sulu/Bundle/TestBundle/Resources/views', 'SuluTest');
        $instance->addPath('/Users/pablolozano/Projects/SuluSchemaOrgBundle/vendor/sulu/sulu/src/Sulu/Bundle/TestBundle/Resources/views', '!SuluTest');
        $instance->addPath('/Users/pablolozano/Projects/SuluSchemaOrgBundle/vendor/symfony/security-bundle/Resources/views', 'Security');
        $instance->addPath('/Users/pablolozano/Projects/SuluSchemaOrgBundle/vendor/symfony/security-bundle/Resources/views', '!Security');
        $instance->addPath('/Users/pablolozano/Projects/SuluSchemaOrgBundle/vendor/sulu/sulu/src/Sulu/Bundle/AdminBundle/Resources/views', 'SuluAdmin');
        $instance->addPath('/Users/pablolozano/Projects/SuluSchemaOrgBundle/vendor/sulu/sulu/src/Sulu/Bundle/AdminBundle/Resources/views', '!SuluAdmin');
        $instance->addPath((\dirname(__DIR__, 5).'/AppBundle/Resources/views'), 'App');
        $instance->addPath((\dirname(__DIR__, 5).'/AppBundle/Resources/views'), '!App');
        $instance->addPath((\dirname(__DIR__, 5).'/templates'));
        $instance->addPath('/Users/pablolozano/Projects/SuluSchemaOrgBundle/vendor/symfony/twig-bridge/Resources/views/Email', 'email');
        $instance->addPath('/Users/pablolozano/Projects/SuluSchemaOrgBundle/vendor/symfony/twig-bridge/Resources/views/Email', '!email');
        $instance->addPath('/Users/pablolozano/Projects/SuluSchemaOrgBundle/vendor/symfony/twig-bridge/Resources/views/Form');

        return $instance;
    }
}
