<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKp5Xx2P\TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKp5Xx2P/TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKp5Xx2P.legacy');

    return;
}

if (!\class_exists(TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKp5Xx2P\TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelDevDebugContainer::class, TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelDevDebugContainer::class, false);
}

return new \ContainerKp5Xx2P\TheCocktail_Bundle_SuluSchemaOrgBundle_Tests_Application_KernelDevDebugContainer([
    'container.build_hash' => 'Kp5Xx2P',
    'container.build_id' => '55501e32',
    'container.build_time' => 1614285626,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKp5Xx2P');
